(function(){'use strict';
const Data=window.LeagueVectorData,PF=window.LeagueVectorProjectionFrontend,$=id=>document.getElementById(id);if(!Data||!PF)return;
let seq=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const leagueId=v=>{const m=String(v).match(/\d{8,}/g);return m?m.at(-1):'';};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function state(msg,type=''){const el=$('experimentalProjectionStatus');if(!el)return;el.className=`projection-state ${type}`.trim();el.textContent=msg;}
function labelStatus(status){return({projection_ready:'Projection ready',rookie_model_required:'Rookie model not yet available',insufficient_history:'Projection unavailable — insufficient NFL history',identity_unresolved:'Projection unavailable — identity unresolved',unsupported_position:'Projection unavailable — unsupported position',missing_required_inputs:'Projection unavailable — missing required inputs',data_unavailable:'Projection unavailable — no validated v0.3 record',source_error:'Projection unavailable — source error'}[status]||status||'Projection unavailable');}
function fmtStat(k){return k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function statMeta(record,k){const model=record.models?.[k],band=record.uncertainty?.[k];return [model?`Model: ${model}`:'',band?`Historical 80% residual range: ${Number(band.p80_low).toFixed(1)}–${Number(band.p80_high).toFixed(1)}`:''].filter(Boolean).join(' • ');}
function renderRows(rows){const query=($('projectionSearch')?.value||'').trim().toLowerCase(),pos=$('projectionPosition')?.value||'ALL';const filtered=rows.filter(r=>(pos==='ALL'||r.position===pos)&&(!query||r.name.toLowerCase().includes(query))).sort((a,b)=>{const ap=a.scoring?.completeness==='complete'?a.scoring.points:-Infinity,bp=b.scoring?.completeness==='complete'?b.scoring.points:-Infinity;return bp-ap||a.name.localeCompare(b.name);});$('experimentalProjectionRows').innerHTML=filtered.map(r=>{if(!r.record||r.projection_status!=='projection_ready')return `<article class="projection-card unavailable"><div><b>${esc(r.name)}</b><span>${esc(r.position)} • ${esc(r.team)}</span></div><div class="projection-unavailable">${esc(labelStatus(r.projection_status))}</div></article>`;const s=r.scoring,stats=Object.entries(r.record.projected_stats).map(([k,v])=>`<li><div><span>${esc(fmtStat(k))}</span>${statMeta(r.record,k)?`<small>${esc(statMeta(r.record,k))}</small>`:''}</div><b>${Number(v).toFixed(1)}</b></li>`).join(''),partial=s?.completeness!=='complete';return `<article class="projection-card"><div class="projection-head"><div><b>${esc(r.name)}</b><span>${esc(r.position)} • ${esc(r.team)}</span></div><div class="projection-points"><strong>${partial?'—':s?.points?.toFixed(1)??'—'}</strong><span>${esc(r.projected_position_rank||'Unranked')}</span></div></div><div class="projection-badges"><span class="exp-badge">EXPERIMENTAL</span><span>Heuristic confidence: ${esc(r.record.confidence||'—')}</span><span>Scoring coverage: ${s?.coverage_pct??0}%</span></div>${s?.unsupported_keys?.length?`<p class="projection-warning">Projected fantasy points are partial and therefore withheld. Unsupported scoring: ${esc(s.unsupported_keys.join(', '))}</p>`:''}<details><summary>Projected stat line</summary><ul class="stat-list">${stats}</ul></details><details><summary>Model details</summary><p>${esc(r.record.model_version||'League Vector v0.3')} • Historical seasons ${esc((r.record.history_seasons||[]).join(', ')||'unavailable')} • Confidence is heuristic, not a probability. Stat ranges are empirical historical residual bands. Experimental only; does not affect dynasty value.</p></details></article>`;}).join('')||'<p class="projection-empty">No matching projection records.</p>';}
function renderTeams(rosters,rows,userMap){const byId=new Map(rows.map(r=>[r.sleeper_id,r]));const teams=rosters.map(roster=>{const starters=(roster.starters||[]).filter(id=>id&&id!=='0'),matched=starters.map(id=>byId.get(String(id))).filter(Boolean),complete=matched.filter(r=>r.scoring?.completeness==='complete'),points=complete.reduce((s,r)=>s+r.scoring.points,0),owner=userMap[roster.owner_id],name=owner?.metadata?.team_name||owner?.display_name||`Roster ${roster.roster_id}`;return{name,points,complete:complete.length,total:starters.length};}).sort((a,b)=>b.points-a.points);$('experimentalTeamProjection').innerHTML=teams.map((t,i)=>`<article class="projection-team"><span>#${i+1}</span><b>${esc(t.name)}</b><strong>${t.points.toFixed(1)}</strong><small>${t.complete}/${t.total} starters with complete experimental projections</small></article>`).join('');}
async function run(){const id=leagueId($('leagueId')?.value);if(!id)return;const my=++seq;$('experimentalProjectionPanel').hidden=false;state('Loading League Vector v0.3 projections…');$('experimentalProjectionRows').innerHTML='';$('experimentalTeamProjection').innerHTML='';try{const [bundle,assetResult]=await Promise.all([Data.leagueBundle(id),Data.request('data/experimental/2026-projections.json',{ttlMs:60*60*1000})]);if(my!==seq)return;const index=PF.buildIndex(assetResult.value),stale=PF.staleStatus(index.projection_date),ids=[...new Set(bundle.rosters.flatMap(r=>r.players||[]))],rows=PF.joinLeaguePlayers(ids,bundle.players,index,bundle.league.scoring_settings||{}),ready=rows.filter(r=>r.projection_status==='projection_ready').length,complete=rows.filter(r=>r.scoring?.completeness==='complete').length;window.__leagueVectorExperimental={rows,index};$('projectionMeta').textContent=`${index.model_version||'League Vector v0.3'} • data through ${index.data_through||'2025'} • ${ready} rostered players matched • ${complete} complete league-scored projections${stale.stale?' • STALE ARTIFACT WARNING':''}`;renderRows(rows);const userMap=Object.fromEntries(bundle.users.map(u=>[u.user_id,u]));renderTeams(bundle.rosters,rows,userMap);state('Experimental projections loaded. Dynasty values are unchanged.','success');$('projectionSearch').oninput=()=>renderRows(rows);$('projectionPosition').onchange=()=>renderRows(rows);}catch(e){console.error(e);state(`Experimental projection data unavailable: ${e.message}`,'error');$('experimentalProjectionRows').innerHTML='<p class="projection-warning">The projection asset could not be loaded. No substitute numbers were generated.</p>';}}
async function scheduleRun(){const requested=leagueId($('leagueId')?.value);if(!requested)return;for(let i=0;i<200;i++){if($('status')?.classList.contains('success'))return run();if($('status')?.classList.contains('error'))return;await sleep(50);}state('Experimental projections were not started because the base league analysis did not finish in time.','error');}
$('go')?.addEventListener('click',()=>setTimeout(scheduleRun,0));$('leagueId')?.addEventListener('keydown',e=>{if(e.key==='Enter')setTimeout(scheduleRun,0);});})();
