(function(){'use strict';
const Data=window.LeagueVectorData,PF=window.LeagueVectorProjectionFrontend,$=id=>document.getElementById(id);if(!Data||!PF)return;
if(!document.querySelector('link[data-lv-projection-browser]')){const link=document.createElement('link');link.rel='stylesheet';link.href='projection-browser-v01.css?v=0.2';link.dataset.lvProjectionBrowser='1';document.head.append(link);}
let seq=0,filterContext={flexPositions:[],superflexPositions:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const leagueId=v=>{const m=String(v).match(/\d{8,}/g);return m?m.at(-1):'';};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function state(msg,type=''){const el=$('experimentalProjectionStatus');if(!el)return;el.className=`projection-state ${type}`.trim();el.textContent=msg;}
function labelStatus(status){return({projection_ready:'Projection ready',rookie_model_required:'Rookie model not yet available',insufficient_history:'Insufficient NFL history',identity_unresolved:'Identity unresolved',unsupported_position:'Unsupported position',missing_required_inputs:'Missing required inputs',data_unavailable:'No validated projection',source_error:'Projection source error'}[status]||status||'Projection unavailable');}
function shortStatus(status){return status==='projection_ready'?'Ready':labelStatus(status);}
function fmtStat(k){return k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function statMeta(record,k){const model=record.models?.[k],band=record.uncertainty?.[k];return [model?`Model: ${model}`:'',band?`Historical residual range (future coverage unvalidated): ${Number(band.p80_low).toFixed(1)}–${Number(band.p80_high).toFixed(1)}`:''].filter(Boolean).join(' • ');}
function deriveFlexArchitecture(league={}){const slots=league.roster_positions||[],normal=new Set(),sflex=new Set();const add=(set,positions)=>positions.forEach(p=>set.add(p));for(const slot of slots){if(slot==='FLEX')add(normal,['RB','WR','TE']);else if(slot==='REC_FLEX')add(normal,['WR','TE']);else if(slot==='WRRB_FLEX')add(normal,['RB','WR']);else if(slot==='SUPER_FLEX')add(sflex,['QB','RB','WR','TE']);}return{flexPositions:[...normal],superflexPositions:[...sflex]};}
function matchesPosition(row,pos){if(pos==='ALL')return true;if(pos==='FLEX')return filterContext.flexPositions.includes(row.position);if(pos==='SFLEX')return filterContext.superflexPositions.includes(row.position);return row.position===pos;}
function ensurePositionNav(){let nav=$('projectionPositionNav');if(!nav){nav=document.createElement('div');nav.id='projectionPositionNav';nav.className='projection-position-nav';nav.setAttribute('role','group');nav.setAttribute('aria-label','Experimental projection position filter');$('projectionSearch')?.closest('.projection-controls')?.before(nav);}const labels=['ALL','QB','RB','WR','TE','FLEX','DL','LB','DB'];nav.innerHTML=labels.map(value=>`<button type="button" class="projection-position-pill${value==='ALL'?' active':''}" data-projection-position="${value}" aria-pressed="${value==='ALL'?'true':'false'}"${value==='FLEX'&&!filterContext.flexPositions.length?' disabled title="No standard flex slot is configured in this league."':''}>${value==='ALL'?'All':value}</button>`).join('');const select=$('projectionPosition');if(select&&!Array.from(select.options).some(o=>o.value==='FLEX'))select.add(new Option('FLEX','FLEX'));for(const button of nav.querySelectorAll('button[data-projection-position]'))button.addEventListener('click',()=>{if(button.disabled)return;const value=button.dataset.projectionPosition;if(select){select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));}for(const peer of nav.querySelectorAll('button')){const active=peer===button;peer.classList.toggle('active',active);peer.setAttribute('aria-pressed',String(active));}});}
function scoringSummary(scoring){const coverage=scoring?.coverage_pct??0,completeness=scoring?.completeness||'unavailable';const label=completeness==='complete'?'Complete':completeness==='partial'?'Partial':'Unavailable';return `${coverage}% scoring coverage · ${label}`;}
function technicalDetails(row,stats){const s=row.scoring,unsupported=s?.unsupported_keys||[];return `<div class="projection-disclosures">${unsupported.length?`<details class="projection-unsupported"><summary>View unsupported scoring</summary><p>${esc(unsupported.join(', '))}</p></details>`:''}<details><summary>Projection details</summary><ul class="stat-list">${stats}</ul></details><details class="projection-technical"><summary>Technical details</summary><p>${esc(row.record.model_version||'League Vector v0.3')} • Historical seasons ${esc((row.record.history_seasons||[]).join(', ')||'unavailable')} • Confidence is heuristic, not a probability. Stat ranges are empirical historical residual bands; future coverage is unvalidated. Experimental only; does not affect dynasty value.</p></details></div>`;}
function renderRows(rows){const query=($('projectionSearch')?.value||'').trim().toLowerCase(),pos=$('projectionPosition')?.value||'ALL';const filtered=rows.filter(r=>matchesPosition(r,pos)&&(!query||r.name.toLowerCase().includes(query))).sort((a,b)=>{const ap=a.scoring?.completeness==='complete'?a.scoring.points:-Infinity,bp=b.scoring?.completeness==='complete'?b.scoring.points:-Infinity;return bp-ap||a.name.localeCompare(b.name);});$('experimentalProjectionRows').innerHTML=filtered.map(r=>{if(!r.record||r.projection_status!=='projection_ready')return `<article class="projection-card unavailable compact" data-position="${esc(r.position)}"><div class="projection-head"><div class="projection-player"><b>${esc(r.name)}</b><span>${esc(r.position)} • ${esc(r.team)}</span></div><span class="projection-status-chip unavailable">${esc(shortStatus(r.projection_status))}</span></div></article>`;const s=r.scoring,stats=Object.entries(r.record.projected_stats).map(([k,v])=>`<li><div><span>${esc(fmtStat(k))}</span>${statMeta(r.record,k)?`<small>${esc(statMeta(r.record,k))}</small>`:''}</div><b>${Number(v).toFixed(1)}</b></li>`).join(''),partial=s?.completeness!=='complete',rank=r.projected_position_rank||'';return `<article class="projection-card compact" data-position="${esc(r.position)}"><div class="projection-head"><div class="projection-player"><b>${esc(r.name)}</b><span>${esc(r.position)} • ${esc(r.team)}</span></div><div class="projection-points"><strong>${partial?'—':s?.points?.toFixed(1)??'—'}</strong>${rank?`<span>${esc(rank)}</span>`:''}</div></div><div class="projection-compact-meta"><span class="projection-status-chip">Ready</span><span>${esc(r.record.confidence||'—')} heuristic confidence</span><span class="projection-scoring-chip ${esc(s?.completeness||'unavailable')}">${esc(scoringSummary(s))}</span></div>${technicalDetails(r,stats)}</article>`;}).join('')||'<p class="projection-empty">No matching projection records.</p>';}
function renderTeams(rosters,rows,userMap){const byId=new Map(rows.map(r=>[r.sleeper_id,r]));const teams=rosters.map(roster=>{const starters=(roster.starters||[]).filter(id=>id&&id!=='0'),matched=starters.map(id=>byId.get(String(id))).filter(Boolean),complete=matched.filter(r=>r.scoring?.completeness==='complete'),points=complete.reduce((s,r)=>s+r.scoring.points,0),owner=userMap[roster.owner_id],name=owner?.metadata?.team_name||owner?.display_name||`Roster ${roster.roster_id}`;return{name,points,complete:complete.length,total:starters.length};}).sort((a,b)=>b.points-a.points);$('experimentalTeamProjection').innerHTML=teams.map((t,i)=>`<article class="projection-team"><span>#${i+1}</span><b>${esc(t.name)}</b><strong>${t.points.toFixed(1)}</strong><small>${t.complete}/${t.total} starters with complete experimental projections</small></article>`).join('');}
async function run(){const id=leagueId($('leagueId')?.value);if(!id)return;const my=++seq;$('experimentalProjectionPanel').hidden=false;state('Loading League Vector v0.3 projections…');$('experimentalProjectionRows').innerHTML='';$('experimentalTeamProjection').innerHTML='';try{const [bundle,assetResult]=await Promise.all([Data.leagueBundle(id),Data.request('data/experimental/2026-projections.json',{ttlMs:60*60*1000})]);if(my!==seq)return;const index=PF.buildIndex(assetResult.value),stale=PF.staleStatus(index.projection_date),ids=[...new Set(bundle.rosters.flatMap(r=>r.players||[]))],rows=PF.joinLeaguePlayers(ids,bundle.players,index,bundle.league.scoring_settings||{}),ready=rows.filter(r=>r.projection_status==='projection_ready').length,complete=rows.filter(r=>r.scoring?.completeness==='complete').length;filterContext=deriveFlexArchitecture(bundle.league);window.__leagueVectorExperimental={rows,index,filterArchitecture:{...filterContext}};$('projectionMeta').textContent=`${index.model_version||'League Vector v0.3'} • data through ${index.data_through||'2025'} • ${ready} rostered players matched • ${complete} complete league-scored projections${stale.stale?' • STALE ARTIFACT WARNING':''}`;ensurePositionNav();renderRows(rows);const userMap=Object.fromEntries(bundle.users.map(u=>[u.user_id,u]));renderTeams(bundle.rosters,rows,userMap);state('Experimental projections loaded. Dynasty values are unchanged.','success');$('projectionSearch').oninput=()=>renderRows(rows);$('projectionPosition').onchange=()=>renderRows(rows);}catch(e){console.error(e);state(`Experimental projection data unavailable: ${e.message}`,'error');$('experimentalProjectionRows').innerHTML='<p class="projection-warning">The projection asset could not be loaded. No substitute numbers were generated.</p>';}}
async function scheduleRun(){const requested=leagueId($('leagueId')?.value);if(!requested)return;for(let i=0;i<200;i++){if($('status')?.classList.contains('success'))return run();if($('status')?.classList.contains('error'))return;await sleep(50);}state('Experimental projections were not started because the base league analysis did not finish in time.','error');}
$('go')?.addEventListener('click',()=>setTimeout(scheduleRun,0));$('leagueId')?.addEventListener('keydown',e=>{if(e.key==='Enter')setTimeout(scheduleRun,0);});})();