(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.LeagueVectorIdentityIdpV04=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const IDP_POSITIONS=['DL','LB','DB'];
const IDP_STATS=['solo_tackles','assisted_tackles','total_tackles','tackles_for_loss','sacks','qb_hits','interceptions','passes_defended','forced_fumbles','fumble_recoveries','defensive_td','safeties'];
function finite(v){return Number.isFinite(Number(v));}
function normalizeText(v){return String(v??'').trim();}
function normalizeName(v){return normalizeText(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\b\.?/g,' ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
function canonicalizeLeagueVectorId(value){let s=normalizeText(value);if(!s)return null;while(s.startsWith('lv:lv:'))s=s.slice(3);if(s.startsWith('lv:'))return s;if(/^(?:gsis|sleeper|nflverse):/.test(s))return `lv:${s}`;return s;}
function trimmedMean(values,trim=0.1){const x=(values||[]).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const cut=Math.min(Math.floor(x.length*trim),Math.floor((x.length-1)/2));const y=x.slice(cut,x.length-cut);return y.reduce((a,b)=>a+b,0)/y.length;}
function median(values){const x=(values||[]).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;}
function mean(values){const x=(values||[]).map(Number).filter(Number.isFinite);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null;}
function buildIdpScoringProfiles(playerSeasons,{seasons=null,minGames=8,trim=0.1}={}){const allowed=seasons?new Set(seasons.map(Number)):null;const out={version:'lv-idp-scoring-profile-v0.1',method:'10pct-trimmed-mean-per-game',min_games:minGames,trim_fraction:trim,seasons:[],positions:{}};const source=(playerSeasons||[]).filter(r=>IDP_POSITIONS.includes(r.position)&&Number(r.games)>=minGames&&(!allowed||allowed.has(Number(r.season))));out.seasons=[...new Set(source.map(r=>Number(r.season)))].sort((a,b)=>a-b);for(const pos of IDP_POSITIONS){const rows=source.filter(r=>r.position===pos);const stats={},sensitivity={};for(const stat of IDP_STATS){const vals=rows.map(r=>{const v=r.per_game?.[stat];return finite(v)?Number(v):null;}).filter(Number.isFinite);stats[stat]=trimmedMean(vals,trim);sensitivity[stat]={mean:mean(vals),median:median(vals),n:vals.length};}out.positions[pos]={sample_size:rows.length,stats_per_game:stats,sensitivity};}return out;}
function setStatus(statusRows,sleeperId,status){const row=(statusRows||[]).find(r=>String(r.sleeper_id)===String(sleeperId));if(row)row.status=status;}
function evidenceFor(record,{sourcePlayersByGsis,historicalPositionByGsis,sleeperPlayers}){const source=sourcePlayersByGsis?.get?.(String(record.gsis_id))||sourcePlayersByGsis?.[String(record.gsis_id)]||null;const sleeper=sleeperPlayers?.[String(record.sleeper_id)]||{};const expectedPos=historicalPositionByGsis?.get?.(String(record.gsis_id))||historicalPositionByGsis?.[String(record.gsis_id)]||source?.football?.position_group||null;const sourceName=source?.name?.normalized||normalizeName(source?.name?.full);const sleeperName=normalizeName(sleeper.full_name||record.name||[sleeper.first_name,sleeper.last_name].filter(Boolean).join(' '));const sourceTeam=normalizeText(source?.football?.team).toUpperCase()||null;const sleeperTeam=normalizeText(sleeper.team||record.team).toUpperCase()||null;return{expected_position:expectedPos,position_match:expectedPos?record.position===expectedPos:null,name_match:sourceName?sourceName===sleeperName:null,team_match:sourceTeam&&sleeperTeam?sourceTeam===sleeperTeam:null,source_name:source?.name?.full||null,source_team:sourceTeam};}
function chooseUnique(group,ctx){const annotated=group.map(record=>({record,evidence:evidenceFor(record,ctx)}));let pool=annotated.filter(x=>x.evidence.position_match!==false);if(pool.length===1)return{winner:pool[0],annotated,reason:'unique_position_match'};const nameMatches=pool.filter(x=>x.evidence.name_match===true);if(nameMatches.length===1)return{winner:nameMatches[0],annotated,reason:'unique_canonical_name_match'};const teamMatches=(nameMatches.length?nameMatches:pool).filter(x=>x.evidence.team_match===true);if(teamMatches.length===1)return{winner:teamMatches[0],annotated,reason:'unique_current_team_match'};return{winner:null,annotated,reason:'ambiguous_duplicate_stable_identity'};}
function assertUnique(records){for(const field of ['sleeper_id','gsis_id','league_vector_player_id']){const seen=new Map(),dups=[];for(const r of records||[]){const raw=r?.[field];if(!raw)continue;const key=field==='league_vector_player_id'?canonicalizeLeagueVectorId(raw):String(raw);if(seen.has(key))dups.push({field,key,first:seen.get(key),second:r});else seen.set(key,r);}if(dups.length){const e=new Error(`Duplicate ${field} identities remain after resolution: ${dups.slice(0,3).map(x=>x.key).join(', ')}`);e.duplicates=dups;throw e;}}return true;}
function resolveProjectionIdentityConflicts(projections,statusRows,ctx={}){const rows=(projections||[]).map(r=>({...r,league_vector_player_id:canonicalizeLeagueVectorId(r.league_vector_player_id)}));const groups=new Map();for(const r of rows){const key=r.gsis_id?`gsis:${r.gsis_id}`:r.league_vector_player_id?`lv:${r.league_vector_player_id}`:`sleeper:${r.sleeper_id}`;const a=groups.get(key)||[];a.push(r);groups.set(key,a);}const keep=new Set(rows),report={version:1,duplicate_groups:0,duplicate_records:0,resolved_groups:0,unresolved_groups:0,resolutions:[]};for(const [key,group] of groups){if(group.length<2)continue;report.duplicate_groups++;report.duplicate_records+=group.length;const choice=chooseUnique(group,ctx);if(choice.winner){report.resolved_groups++;for(const r of group){if(r===choice.winner.record)continue;keep.delete(r);setStatus(statusRows,r.sleeper_id,'identity_unresolved');}report.resolutions.push({stable_identity:key,status:'resolved',kept_sleeper_id:String(choice.winner.record.sleeper_id),reason:choice.reason,candidates:choice.annotated.map(x=>({sleeper_id:String(x.record.sleeper_id),name:x.record.name,position:x.record.position,team:x.record.team,evidence:x.evidence}))});}else{report.unresolved_groups++;for(const r of group){keep.delete(r);setStatus(statusRows,r.sleeper_id,'identity_unresolved');}report.resolutions.push({stable_identity:key,status:'unresolved',kept_sleeper_id:null,reason:choice.reason,candidates:choice.annotated.map(x=>({sleeper_id:String(x.record.sleeper_id),name:x.record.name,position:x.record.position,team:x.record.team,evidence:x.evidence}))});}}
const output=rows.filter(r=>keep.has(r));assertUnique(output);report.output_records=output.length;report.removed_records=rows.length-output.length;return{projections:output,statusRows,report};}
return{IDP_POSITIONS,IDP_STATS,canonicalizeLeagueVectorId,trimmedMean,median,mean,buildIdpScoringProfiles,evidenceFor,resolveProjectionIdentityConflicts,assertUnique};});