(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.LeagueVectorProjectionV03=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const B=require('./projection-benchmark-v08.js');const Ridge=require('./ridge-v02.js');
const VERSION='lv-projection-system-v0.3';const POSITIONS=B.POSITIONS;const TARGETS=B.TARGETS;
const RARE=new Set(['interceptions','rushing_td','receiving_td','sacks','forced_fumbles','fumble_recoveries','defensive_td','safeties']);
const REF_RULES={OFFENSE:{passing_yards:.04,passing_td:4,interceptions:-2,rushing_yards:.1,rushing_td:6,receptions:1,receiving_yards:.1,receiving_td:6},IDP:{solo_tackles:1.5,assisted_tackles:.75,tackles_for_loss:2,sacks:4,qb_hits:1,interceptions:6,passes_defended:1.5,forced_fumbles:3,fumble_recoveries:3,defensive_td:6,safeties:4}};
const REQUIRED={QB:['passing_yards','passing_td','interceptions','rushing_yards','rushing_td'],RB:['rushing_yards','rushing_td','receptions','receiving_yards','receiving_td'],WR:['rushing_yards','rushing_td','receptions','receiving_yards','receiving_td'],TE:['rushing_yards','rushing_td','receptions','receiving_yards','receiving_td'],DL:Object.keys(REF_RULES.IDP),LB:Object.keys(REF_RULES.IDP),DB:Object.keys(REF_RULES.IDP)};
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;const median=a=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;};const quantile=(a,p)=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),v=(x.length-1)*p,l=Math.floor(v),h=Math.ceil(v);return l===h?x[l]:x[l]+(x[h]-x[l])*(v-l);};
function index(rows){const m=new Map();for(const r of rows){const a=m.get(r.gsis_id)||[];a.push(r);m.set(r.gsis_id,a);}for(const a of m.values())a.sort((x,y)=>x.season-y.season);return m;}function history(i,id,s,n=3){return(i.get(id)||[]).filter(r=>r.season<s).slice(-n).reverse();}
function feature(h,t,birth,s,useAge=true){if(!h[0]||!Number.isFinite(h[0].totals[t]))return null;const vals=[h[0].totals[t],h[1]?.totals?.[t]??null,h[2]?.totals?.[t]??null,h[0].games,h[0].per_game?.[t]??null];if(useAge)vals.push(Ridge.ageOn(birth,s));return vals;}
function weighted(h,t){const w=[.6,.3,.1];let n=0,d=0;for(let i=0;i<Math.min(h.length,3);i++){const v=h[i]?.totals?.[t];if(Number.isFinite(v)){n+=v*w[i];d+=w[i];}}return d?n/d:null;}
function priorPositionMean(rows,p,t,before){const vals=rows.filter(r=>r.position===p&&r.season<before&&Number.isFinite(r.totals[t])).map(r=>r.totals[t]);return mean(vals);}
function shrink(h,rows,p,t,s){const w=weighted(h,t),avg=priorPositionMean(rows,p,t,s);if(!Number.isFinite(w))return null;if(!Number.isFinite(avg))return w;return w*.7+avg*.3;}
function train(rows,p,t,before,birth,useAge){const i=index(rows),X=[],y=[];for(const r of rows){if(r.position!==p||r.season>=before||!Number.isFinite(r.totals[t]))continue;const f=feature(history(i,r.gsis_id,r.season),t,birth[r.gsis_id],r.season,useAge);if(f){X.push(f);y.push(r.totals[t]);}}return{X,y};}
function tuneAlpha(rows,p,t,target,birth,useAge){const grid=[.01,.1,1,10,100,1000],validation=target-1,i=index(rows),actual=rows.filter(r=>r.position===p&&r.season===validation&&Number.isFinite(r.totals[t])),tr=train(rows,p,t,validation,birth,useAge);if(tr.X.length<20||actual.length<5)return 10;let best={alpha:10,mae:Infinity};for(const alpha of grid){const m=Ridge.fit(tr.X,tr.y,alpha);if(!m)continue;const e=[];for(const r of actual){const f=feature(history(i,r.gsis_id,validation),t,birth[r.gsis_id],validation,useAge);if(f)e.push(Math.abs(m.predict(f)-r.totals[t]));}const mae=mean(e);if(Number.isFinite(mae)&&mae<best.mae)best={alpha,mae};}return best.alpha;}
function predictFold(rows,target,birth){const i=index(rows),actual=rows.filter(r=>r.season===target),cache=new Map(),out=[];for(const a of actual){const h=history(i,a.gsis_id,target);if(!h.length)continue;for(const t of TARGETS[a.position]||[]){if(!Number.isFinite(a.totals[t]))continue;const models={weighted_603010:weighted(h,t)};for(const useAge of [false,true]){const name=useAge?'ridge_age_v03':'ridge_noage_v03',k=`${a.position}|${t}|${name}`;if(!cache.has(k)){const alpha=tuneAlpha(rows,a.position,t,target,birth,useAge),tr=train(rows,a.position,t,target,birth,useAge);cache.set(k,{alpha,model:Ridge.fit(tr.X,tr.y,alpha),n:tr.y.length});}const c=cache.get(k),f=feature(h,t,birth[a.gsis_id],target,useAge);models[name]=c.model&&f?c.model.predict(f):null;}if(RARE.has(t))models.shrink_v03=shrink(h,rows,a.position,t,target);for(const [model,prediction] of Object.entries(models))if(Number.isFinite(prediction))out.push({gsis_id:a.gsis_id,position:a.position,target:t,target_season:target,model,prediction,actual:a.totals[t],history_seasons:h.map(x=>x.season)});}}return out;}
function stats(rows){if(!rows.length)return{n:0,mae:null,rmse:null,median_ae:null,bias:null};const e=rows.map(r=>r.prediction-r.actual),ae=e.map(Math.abs);return{n:rows.length,mae:mean(ae),rmse:Math.sqrt(mean(e.map(x=>x*x))),median_ae:median(ae),bias:mean(e)};}
function compare(predictions,folds){const result=[];for(const p of POSITIONS)for(const t of TARGETS[p]||[]){const models=[...new Set(predictions.filter(x=>x.position===p&&x.target===t).map(x=>x.model))];if(!models.includes('weighted_603010'))continue;const bRows=predictions.filter(x=>x.position===p&&x.target===t&&x.model==='weighted_603010'),b=stats(bRows);let winner={model:'weighted_603010',...b,improvement_pct:0,fold_wins:folds.length};for(const m of models.filter(x=>x!=='weighted_603010')){const r=predictions.filter(x=>x.position===p&&x.target===t&&x.model===m),s=stats(r),wins=folds.filter(f=>{const a=stats(r.filter(x=>x.target_season===f)),q=stats(bRows.filter(x=>x.target_season===f));return Number.isFinite(a.mae)&&Number.isFinite(q.mae)&&a.mae<q.mae;}).length,imp=b.mae?((b.mae-s.mae)/b.mae)*100:null;if(Number.isFinite(imp)&&imp>=2&&wins>=Math.ceil(folds.length/2)&&s.mae<winner.mae)winner={model:m,...s,improvement_pct:imp,fold_wins:wins};}
const age=stats(predictions.filter(x=>x.position===p&&x.target===t&&x.model==='ridge_age_v03')),noage=stats(predictions.filter(x=>x.position===p&&x.target===t&&x.model==='ridge_noage_v03'));result.push({position:p,target:t,baseline:b,selected:winner,age_ablation:{with_age_mae:age.mae,without_age_mae:noage.mae,age_delta_mae:Number.isFinite(age.mae)&&Number.isFinite(noage.mae)?age.mae-noage.mae:null,preferred:Number.isFinite(age.mae)&&Number.isFinite(noage.mae)?(age.mae<noage.mae?'with_age':'without_age'):'insufficient_evidence'},experimental:true,production_eligible:false});}return result;}
function scoreReference(totals,p){const rules=['DL','LB','DB'].includes(p)?REF_RULES.IDP:REF_RULES.OFFENSE;return Object.entries(rules).reduce((s,[k,w])=>s+(Number.isFinite(totals[k])?totals[k]:0)*w,0);}
function fantasyBacktest(pred,selection){const sel=new Map(selection.map(x=>[`${x.position}|${x.target}`,x.selected.model])),groups=new Map();for(const r of pred){if(sel.get(`${r.position}|${r.target}`)!==r.model)continue;const k=`${r.gsis_id}|${r.position}|${r.target_season}`,x=groups.get(k)||{gsis_id:r.gsis_id,position:r.position,target_season:r.target_season,pred:{},actual:{}};x.pred[r.target]=r.prediction;x.actual[r.target]=r.actual;groups.set(k,x);}const complete=[];for(const x of groups.values()){const req=REQUIRED[x.position]||[],missing=req.filter(k=>!Number.isFinite(x.pred[k])||!Number.isFinite(x.actual[k]));if(!missing.length)complete.push({...x,predicted_points:scoreReference(x.pred,x.position),actual_points:scoreReference(x.actual,x.position)});}const by=[];for(const p of POSITIONS){const rows=complete.filter(x=>x.position===p).map(x=>({prediction:x.predicted_points,actual:x.actual_points}));if(rows.length)by.push({position:p,...stats(rows)});}return{complete_players:complete.length,by_position:by};}
function uncertainty(pred,selection){const sel=new Map(selection.map(x=>[`${x.position}|${x.target}`,x.selected.model])),out=[];for(const p of POSITIONS)for(const t of TARGETS[p]||[]){const model=sel.get(`${p}|${t}`),rows=pred.filter(x=>x.position===p&&x.target===t&&x.model===model),abs=rows.map(x=>Math.abs(x.prediction-x.actual));if(abs.length<10)continue;const bands={p50:quantile(abs,.5),p80:quantile(abs,.8),p90:quantile(abs,.9)};out.push({position:p,target:t,model,n:abs.length,...bands,observed_coverage:{p50:mean(abs.map(x=>x<=bands.p50?1:0)),p80:mean(abs.map(x=>x<=bands.p80?1:0)),p90:mean(abs.map(x=>x<=bands.p90?1:0))}});}return out;}
function finalModel(rows,p,t,birth,selection,targetSeason=2026){const name=selection.selected.model,i=index(rows);return{name,buildFor(id){const h=history(i,id,targetSeason);if(!h.length)return null;if(name==='weighted_603010')return weighted(h,t);if(name==='shrink_v03')return shrink(h,rows,p,t,targetSeason);const useAge=name==='ridge_age_v03',alpha=tuneAlpha(rows,p,t,targetSeason,birth,useAge),tr=train(rows,p,t,targetSeason,birth,useAge),m=Ridge.fit(tr.X,tr.y,alpha),f=feature(h,t,birth[id],targetSeason,useAge);return m&&f?m.predict(f):null;}};}
function sanitizeLine(stats,position){const corrections=[];const out={...stats};for(const [k,v] of Object.entries(out))if(Number.isFinite(v)&&v<0){corrections.push({field:k,original:v,corrected:0,rule:'nonnegative_counting_stat'});out[k]=0;}function cap(a,b){if(Number.isFinite(out[a])&&Number.isFinite(out[b])&&out[a]>out[b]){corrections.push({field:a,original:out[a],corrected:out[b],rule:`${a}<=${b}`});out[a]=out[b];}}cap('completions','attempts');cap('receptions','targets');cap('receiving_td','receptions');cap('rushing_td','carries');return{stats:out,corrections};}
function confidence(historyCount,missing,identityResolved=true){let score=0;if(identityResolved)score++;if(historyCount>=3)score+=2;else if(historyCount>=2)score++;if(!missing.length)score+=2;return{label:score>=5?'High':score>=3?'Medium':'Low',type:'HEURISTIC'};}
function sleeperScore(stats,scoring={}){const map={pass_yd:'passing_yards',pass_td:'passing_td',pass_int:'interceptions',rush_yd:'rushing_yards',rush_td:'rushing_td',rec:'receptions',rec_yd:'receiving_yards',rec_td:'receiving_td',idp_tkl_solo:'solo_tackles',idp_tkl_ast:'assisted_tackles',idp_tkl_loss:'tackles_for_loss',idp_sack:'sacks',idp_qb_hit:'qb_hits',idp_int:'interceptions',idp_pass_def:'passes_defended',idp_ff:'forced_fumbles',idp_fum_rec:'fumble_recoveries',idp_def_td:'defensive_td',idp_safe:'safeties'};let points=0,supported=0,unsupported=[];for(const [key,w] of Object.entries(scoring||{})){const stat=map[key];if(!stat){if(Number(w)!==0)unsupported.push(key);continue;}if(Number.isFinite(stats[stat])){points+=stats[stat]*Number(w||0);supported++;}else if(Number(w)!==0)unsupported.push(key);}return{points,supported_keys:supported,unsupported_keys:unsupported,complete:unsupported.length===0};}
return{VERSION,POSITIONS,TARGETS,REQUIRED,RARE,REF_RULES,index,history,feature,weighted,shrink,train,tuneAlpha,predictFold,stats,compare,scoreReference,fantasyBacktest,uncertainty,finalModel,sanitizeLine,confidence,sleeperScore};});