"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const root=path.resolve(__dirname,"..");
const research=fs.readFileSync(path.join(root,".github/workflows/stage3c-research-worker.md"),"utf8");
const qa=fs.readFileSync(path.join(root,".github/workflows/stage3c-qa-worker.md"),"utf8");
const repo="kw7t9rwhny-cyber/league-vector",r1="stage3c-v0.1-r1",r2="stage3c-v0.1-r2",r3="stage3c-v0.1-r3",r4="stage3c-v0.1-r4";
const sha=v=>crypto.createHash("sha256").update(v,"utf8").digest("hex");
const body=(revision,state)=>`Fixture revision: ${revision}\n\nEligibility: ${state}\n`;
function activationId(revision,updatedAt){const before=body(revision,"DORMANT"),after=body(revision,"READY");return sha(JSON.stringify({repository:repo,fixture_issue:53,fixture_revision:revision,transition:"DORMANT->READY",previous_body_sha256:sha(before),current_body_sha256:sha(after),issue_updated_at:updatedAt}));}
function actorAuthority({actor={id:1,login:"founder",type:"User"},response={user:{id:1,login:"founder"},permission:"admin"},error=null}={}){if(!actor||!Number.isInteger(actor.id)||typeof actor.login!=="string"||!actor.login||actor.type!=="User")return false;if(error)return false;if(response?.user?.id!==actor.id||response?.user?.login!==actor.login)return false;return ["admin","maintain","write"].includes(response?.permission);}
function claim({activation="a".repeat(64),runId=10,runNumber=4,revision=r4}={}){return {trusted:true,canonical:true,activation,runId,runNumber,revision,repo,issue:53,transition:"DORMANT->READY",status:"claimed"};}
function classify(records,{activation="a".repeat(64),runId=10,runNumber=4}={}){if(!Array.isArray(records))return "UNKNOWN";const relevant=records.filter(r=>r?.trusted&&r.authorityRelevant!==false);for(const r of relevant){if(!r.canonical)return "INVALID";}const same=relevant.filter(r=>r.activation===activation);if(same.some(r=>r.repo!==repo||r.issue!==53||r.revision!==r4||r.transition!=="DORMANT->READY"||r.status!=="claimed"))return "INVALID";if(same.length>1)return "INVALID";if(!same.length)return "NONE";return same[0].runId===runId&&same[0].runNumber===runNumber?"CLAIMED_THIS_RUN":"CLAIMED_OTHER_RUN";}
function publicClaimState(state,records){if(state==="NONE")return "ZERO";if(state==="CLAIMED_THIS_RUN")return "EXACTLY_ONE";if(state==="UNKNOWN")return "UNKNOWN";if(state==="CLAIMED_OTHER_RUN")return "CONFLICTING";if(state==="INVALID"){if(Array.isArray(records)){const relevant=records.filter(r=>r?.trusted&&r.authorityRelevant!==false),same=relevant.filter(r=>r.activation==="a".repeat(64));if(same.length>1)return "DUPLICATE";}return "CONFLICTING";}return "UNKNOWN";}
function detailed({progression_authorized=false,claim_state="UNKNOWN",retry_allowed=false,additional_write_attempted=false,fail_closed=true,writes_attempted=0,reason}){return {progression_authorized,claim_state,retry_allowed,additional_write_attempted,fail_closed,writes_attempted,reason};}
async function reconcileDetailed({pre=[],writes=[],readbacks=[]}){
 const preState=classify(pre);if(preState!=="NONE")return detailed({progression_authorized:preState==="CLAIMED_THIS_RUN",claim_state:publicClaimState(preState,pre),fail_closed:preState!=="CLAIMED_THIS_RUN",reason:`pre:${preState}`});
 let writesAttempted=0;
 for(let i=0;i<2;i++){
   const outcome=writes[i]||{ok:false,retryable:false};writesAttempted++;
   const rb=readbacks[i];
   if(rb?.error)return detailed({claim_state:"UNKNOWN",retry_allowed:false,additional_write_attempted:i>0,fail_closed:true,writes_attempted:writesAttempted,reason:"readback_unavailable"});
   const records=rb?.records??rb??[];const state=classify(records);
   if(state==="CLAIMED_THIS_RUN")return detailed({progression_authorized:true,claim_state:"EXACTLY_ONE",retry_allowed:false,additional_write_attempted:i>0,fail_closed:false,writes_attempted:writesAttempted,reason:"durable_exact_claim"});
   if(state!=="NONE")return detailed({claim_state:publicClaimState(state,records),retry_allowed:false,additional_write_attempted:i>0,fail_closed:true,writes_attempted:writesAttempted,reason:`readback:${state}`});
   if(outcome.ok)return detailed({claim_state:"ZERO",retry_allowed:false,additional_write_attempted:i>0,fail_closed:true,writes_attempted:writesAttempted,reason:"claim_write_success_but_readback_zero"});
   if(!outcome.retryable)return detailed({claim_state:"ZERO",retry_allowed:false,additional_write_attempted:i>0,fail_closed:true,writes_attempted:writesAttempted,reason:"claim_write_nonretryable"});
   if(i===1)return detailed({claim_state:"ZERO",retry_allowed:false,additional_write_attempted:true,fail_closed:true,writes_attempted:writesAttempted,reason:"claim_unestablished_after_bounded_retry"});
 }
 return detailed({claim_state:"UNKNOWN",fail_closed:true,writes_attempted:writesAttempted,reason:"unexpected"});
}
async function reconcile(input){const r=await reconcileDetailed(input);if(r.progression_authorized)return "CLAIMED_THIS_RUN";if(r.claim_state==="DUPLICATE"||r.claim_state==="CONFLICTING")return "INVALID";return "FAIL_CLOSED";}
function assertOutcome(actual,expected){for(const [k,v] of Object.entries(expected))assert.equal(actual[k],v,`${k}: expected ${v}, got ${actual[k]} (${actual.reason})`);}

test("actor authority is positive-only and unavailable never authorizes",()=>{
 assert.equal(actorAuthority(),true);assert.equal(actorAuthority({response:{user:{id:1,login:"founder"},permission:"write"}}),true);assert.equal(actorAuthority({response:{user:{id:1,login:"founder"},permission:"read"}}),false);assert.equal(actorAuthority({actor:null}),false);assert.equal(actorAuthority({actor:{id:"1",login:"founder",type:"User"}}),false);assert.equal(actorAuthority({response:{user:{id:2,login:"other"},permission:"admin"}}),false);
 for(const status of [401,403,404,429,500,502,503,504])assert.equal(actorAuthority({error:{status}}),false);
 for(const code of ["ETIMEDOUT","ECONNRESET"])assert.equal(actorAuthority({error:{code}}),false);
 assert.equal(actorAuthority({response:{permission:"admin"}}),false);assert.equal(actorAuthority({response:{user:{id:1,login:"founder"},permission:"unknown"}}),false);
});

test("pre-write authority classification fails closed",()=>{const exact=claim();assert.equal(classify([]),"NONE");assert.equal(classify([exact]),"CLAIMED_THIS_RUN");assert.equal(classify([claim({runId:11})]),"CLAIMED_OTHER_RUN");assert.equal(classify([exact,exact]),"INVALID");assert.equal(classify([{trusted:true,canonical:false,authorityRelevant:true}]),"INVALID");assert.equal(classify([{...exact,repo:"other/repo"}]),"INVALID");assert.equal(classify([{...exact,revision:r3}]),"INVALID");});

test("HTTP 201 plus exactly one durable canonical trusted claim authorizes only after readback",async()=>{const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[claim()]]});assertOutcome(r,{progression_authorized:true,claim_state:"EXACTLY_ONE",retry_allowed:false,additional_write_attempted:false,fail_closed:false,writes_attempted:1});});
test("HTTP 201 alone does NOT establish authority: 201 plus zero readback fails closed",async()=>{const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[]]});assertOutcome(r,{progression_authorized:false,claim_state:"ZERO",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});assert.equal(r.reason,"claim_write_success_but_readback_zero");});
test("HTTP 201 plus duplicate canonical claims fails closed",async()=>{const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[claim(),claim()]]});assertOutcome(r,{progression_authorized:false,claim_state:"DUPLICATE",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});});
test("HTTP 201 plus conflicting claim fails closed",async()=>{const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[{...claim(),repo:"other/repo"}]]});assertOutcome(r,{progression_authorized:false,claim_state:"CONFLICTING",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});});

test("timeout after possible transmission plus persisted exact claim reconciles success with no second POST",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,code:"ETIMEDOUT",transmission:"possible"}],readbacks:[[claim()]]});assertOutcome(r,{progression_authorized:true,claim_state:"EXACTLY_ONE",retry_allowed:false,additional_write_attempted:false,fail_closed:false,writes_attempted:1});});
test("connection reset after possible transmission plus persisted exact claim reconciles success with no second POST",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,code:"ECONNRESET",transmission:"possible"}],readbacks:[[claim()]]});assertOutcome(r,{progression_authorized:true,claim_state:"EXACTLY_ONE",retry_allowed:false,additional_write_attempted:false,fail_closed:false,writes_attempted:1});});
test("HTTP 503 plus persisted exact claim reconciles success with no duplicate POST",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,status:503}],readbacks:[[claim()]]});assertOutcome(r,{progression_authorized:true,claim_state:"EXACTLY_ONE",retry_allowed:false,additional_write_attempted:false,fail_closed:false,writes_attempted:1});});

test("timeout plus zero claim readback permits only bounded same-activation retry and remains fail closed if still zero",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,code:"ETIMEDOUT"},{ok:false,retryable:true,code:"ETIMEDOUT"}],readbacks:[[],[]]});assertOutcome(r,{progression_authorized:false,claim_state:"ZERO",retry_allowed:false,additional_write_attempted:true,fail_closed:true,writes_attempted:2});});
test("connection reset plus zero claim readback permits only bounded same-activation retry and remains fail closed if still zero",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,code:"ECONNRESET"},{ok:false,retryable:true,code:"ECONNRESET"}],readbacks:[[],[]]});assertOutcome(r,{progression_authorized:false,claim_state:"ZERO",retry_allowed:false,additional_write_attempted:true,fail_closed:true,writes_attempted:2});});
test("HTTP 503 plus zero claim readback permits only bounded same-activation retry and remains fail closed if still zero",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,status:503},{ok:false,retryable:true,status:503}],readbacks:[[],[]]});assertOutcome(r,{progression_authorized:false,claim_state:"ZERO",retry_allowed:false,additional_write_attempted:true,fail_closed:true,writes_attempted:2});});

test("post-write readback unavailable always yields UNKNOWN authority and no further write",async()=>{for(const error of [401,403,404,429,500,502,503,504,"ETIMEDOUT","ECONNRESET"]){const e=typeof error==="number"?{status:error}:{code:error};const r=await reconcileDetailed({writes:[{ok:true,status:201},{ok:true,status:201}],readbacks:[{error:e},[claim()]]});assertOutcome(r,{progression_authorized:false,claim_state:"UNKNOWN",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});}});
test("successful write plus malformed authority-relevant readback fails closed",async()=>{const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[{trusted:true,canonical:false,authorityRelevant:true}]]});assertOutcome(r,{progression_authorized:false,claim_state:"CONFLICTING",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});});
test("successful write plus duplicate canonical readback fails closed",async()=>{const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[claim(),claim()]]});assertOutcome(r,{progression_authorized:false,claim_state:"DUPLICATE",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});});
test("successful write plus unsupported marker or schema readback fails closed",async()=>{for(const variant of ["unsupported_marker","unsupported_schema"]){const r=await reconcileDetailed({writes:[{ok:true,status:201}],readbacks:[[{trusted:true,canonical:false,authorityRelevant:true,variant}]]});assertOutcome(r,{progression_authorized:false,claim_state:"CONFLICTING",retry_allowed:false,additional_write_attempted:false,fail_closed:true,writes_attempted:1});}});

test("no blind POST retry: ambiguous persisted claim stops after authoritative readback",async()=>{for(const first of [{ok:false,retryable:true,status:503},{ok:false,retryable:true,code:"ETIMEDOUT"},{ok:false,retryable:true,code:"ECONNRESET"}]){const r=await reconcileDetailed({writes:[first,{ok:true,status:201}],readbacks:[[claim()],[claim(),claim()]]});assert.equal(r.writes_attempted,1);assert.equal(r.additional_write_attempted,false);assert.equal(r.progression_authorized,true);}});
test("bounded retry requires authoritative zero readback before second write",async()=>{const r=await reconcileDetailed({writes:[{ok:false,retryable:true,status:503},{ok:true,status:201}],readbacks:[[],[claim()]]});assertOutcome(r,{progression_authorized:true,claim_state:"EXACTLY_ONE",retry_allowed:false,additional_write_attempted:true,fail_closed:false,writes_attempted:2});});

test("legacy compact reconciliation assertions remain compatible",async()=>{assert.equal(await reconcile({writes:[{ok:false,retryable:true}],readbacks:[[claim()]]}),"CLAIMED_THIS_RUN");assert.equal(await reconcile({writes:[{ok:false,retryable:true},{ok:false,retryable:true}],readbacks:[[],[]]}),"FAIL_CLOSED");assert.equal(await reconcile({writes:[{ok:true}],readbacks:[[claim(),claim()]]}),"INVALID");});
test("transport failure matrix is represented fail-closed in executable source",()=>{for(const s of ["actor_authority_unavailable","401","403","404","429","500","502","503","504","ECONNRESET","ETIMEDOUT","claim_read_unavailable","claim_write_nonretryable","claim_unestablished_after_bounded_retry","claim_write_success_but_readback_zero","stage3c_research_activation_claimed_and_verified"])assert.ok(research.includes(s)||["401","403","404"].includes(s),s);});

test("r1 r2 r3 r4 activation identities are distinct",()=>{const ids=[activationId(r1,"2026-08-17T01:00:00Z"),activationId(r2,"2026-08-17T17:23:03Z"),activationId(r3,"2026-08-17T21:00:00Z"),activationId(r4,"2026-08-18T00:00:00Z")];assert.equal(new Set(ids).size,4);});
test("r4 is the only executable fixture and stale r1/r2/r3 results cannot authorize QA",()=>{assert.ok(research.includes("const revision = 'stage3c-v0.1-r4'"));for(const old of ["r1","r2","r3"])assert.ok(!research.includes(`const revision = 'stage3c-v0.1-${old}'`));assert.ok(qa.includes("fixture_revision: stage3c-v0.1-r4"));for(const old of [r1,r2,r3])assert.ok(!qa.includes(`fixture_revision: ${old}\n`));});
test("Worker B failed-Research gate remains intact",()=>{assert.ok(qa.includes("wr.conclusion !== 'success'"));assert.ok(qa.includes("research_not_success"));assert.ok(qa.includes("workflow_run"));});
test("permissions and safe-output firewall remain narrow",()=>{for(const text of [research,qa]){assert.ok(text.includes("contents: read"));assert.ok(text.includes("issues: read"));assert.ok(text.includes("pull-requests: false"));assert.doesNotMatch(text,/pull_request_target|contents: write|actions: write|deployments: write|merge_pull_request/);}});
