"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,".."),read=p=>fs.readFileSync(path.join(root,p),"utf8");
const research=read(".github/workflows/stage3c-research-worker.md"),qa=read(".github/workflows/stage3c-qa-worker.md"),compile=read(".github/workflows/stage3c-agentic-compile-validation.yml"),docs=read("docs/development-orchestrator-stage3c-two-worker-proof-v01.md"),locks=[read(".github/workflows/stage3c-research-worker.lock.yml"),read(".github/workflows/stage3c-qa-worker.lock.yml")];
const dormant="Fixture revision: stage3c-v0.1-r1\n\nEligibility: DORMANT\n",ready="Fixture revision: stage3c-v0.1-r1\n\nEligibility: READY\n";
function eligible({repo="kw7t9rwhny-cyber/league-vector",issue=53,title="AGENT SPIKE TEST — harmless two-worker handoff",before,after,attempt="1"}){const val=b=>{if(typeof b!=="string")return null;const m=[...b.matchAll(/^Eligibility: ([^\r\n]+)$/gm)];return m.length===1?m[0][1]:null},rev=b=>typeof b==="string"?[...b.matchAll(/^Fixture revision: stage3c-v0\.1-r1$/gm)].length:0;if(repo!=="kw7t9rwhny-cyber/league-vector"||issue!==53||title!=="AGENT SPIKE TEST — harmless two-worker handoff"||attempt!=="1"||typeof before!=="string"||typeof after!=="string"||rev(before)!==1||rev(after)!==1||val(before)!=="DORMANT"||val(after)!=="READY")return false;return after===before.replace(/^Eligibility: DORMANT$/m,"Eligibility: READY")}
function job(lock,name){const marker=`\n  ${name}:\n`,i=lock.indexOf(marker);assert.notEqual(i,-1);const rest=lock.slice(i+marker.length),m=rest.match(/\n  [A-Za-z0-9_-]+:\n/);return m?rest.slice(0,m.index):rest}
test("Worker A exact transition adversarial matrix",()=>{assert.equal(eligible({before:dormant,after:ready}),true);for(const a of [{before:ready,after:ready},{before:dormant.replace("DORMANT","UNKNOWN"),after:ready},{before:undefined,after:ready},{before:dormant,after:undefined},{before:dormant,after:ready.replace("READY","ready")},{before:dormant,after:ready+"extra\n"},{before:dormant,after:ready,issue:54},{before:dormant,after:ready,repo:"attacker/repo"},{before:dormant,after:ready,attempt:"2"},{before:dormant+"Eligibility: DORMANT\n",after:ready}])assert.equal(eligible(a),false);for(const x of ["replayed_run","wrong_repository","wrong_issue","missing_previous_body","missing_current_body","invalid_fixture_revision","previous_not_dormant","current_not_ready","body_changed_beyond_authorized_transition"])assert.ok(research.includes(x));assert.ok(research.includes("needs.pre_activation.outputs.exact_transition_result == 'success'"));});
test("Worker B binds exact Research authority before agent",()=>{for(const x of ["wr.name !== 'Stage 3C Research Worker A'","wr.path !== '.github/workflows/stage3c-research-worker.lock.yml'","wr.event !== 'issues'","wr.head_branch !== 'main'","wr.conclusion !== 'success'","wr.run_attempt !== 1","issue_number: 53","researchForRun.length !== 1","github-actions[bot]","research_result_outside_authoritative_window","prior_authoritative_qa_result","needs.pre_activation.outputs.research_authority_result == 'success'"])assert.ok(qa.includes(x),x);});
test("duplicate retry and downstream fanout are bounded",()=>{for(const x of ["stage3c-research-fixture-53","cancel-in-progress: true","GITHUB_RUN_ATTEMPT !== '1'"])assert.ok(research.includes(x));for(const x of ["stage3c-qa-${{ github.event.workflow_run.id }}","cancel-in-progress: false","priorQa.length !== 0"])assert.ok(qa.includes(x));assert.doesNotMatch(qa,/dispatch-workflow|call-workflow/);for(const s of [research,qa])assert.ok(s.includes("timeout-minutes: 10"));});
test("generated executable agent jobs are read-only",()=>{for(const lock of locks){const a=job(lock,"agent");assert.ok(a.includes("contents: read")&&a.includes("issues: read")&&a.includes("GITHUB_READ_ONLY"));assert.doesNotMatch(a,/:\s*write/);for(const x of ["contents: write","pull-requests: write","actions: write","deployments: write","packages: write","administration: write","statuses: write","checks: write"])assert.ok(!lock.includes(x),x);}});
test("generated safe-output authority is fixed Issue 53 comment only",()=>{for(const lock of locks){const safe=job(lock,"safe_outputs");assert.ok(safe.includes("issues: write"));assert.doesNotMatch(safe,/contents: write|pull-requests: write|actions: write/);const m=lock.match(/GH_AW_SAFE_OUTPUTS_HANDLER_CONFIG: "[^\n]+"/);assert.ok(m);const c=m[0];for(const x of ["add_comment","target\\\":\\\"53","max\\\":1","report_incomplete"])assert.ok(c.includes(x),x);assert.ok(!c.includes("create_report_incomplete_issue"));for(const x of ["create_pull_request","add_labels","remove_labels","merge_pull_request","push_to_pull_request_branch","update_release","dispatch_workflow","create_issue"])assert.ok(!c.includes(x),x);assert.ok(lock.includes('GH_AW_REPORT_INCOMPLETE_CREATE_ISSUE: "false"'));assert.ok(lock.includes('GH_AW_FAILURE_REPORT_AS_ISSUE: "false"'));}});
test("source closes secondary write channels",()=>{for(const s of [research,qa])for(const x of ["report-failure-as-issue: false","report-incomplete:\n    create-issue: false","missing-tool: false","missing-data: false","noop: false","target: \"53\"","max: 1","pull-requests: false","discussions: false"])assert.ok(s.includes(x),x);});
test("secret boundary stays native Codex",()=>{for(const s of [research,qa,compile])assert.doesNotMatch(s,/OPENAI_API_KEY|CODEX_API_KEY|github_pat_|gh[pousr]_/i);for(const lock of locks){for(const x of ['"OPENAI_API_KEY"','"agent_id":"codex"','"compiler_version":"v0.86.2"','"strict":true'])assert.ok(lock.includes(x),x);}});
test("verified compiler is read-only and deterministic",()=>{for(const x of ["v0.86.2/linux-amd64","b8fd100d1d56a77b842ad28375ff361215a5aa1277db6b9a05d70054cde7260e","6aab9e5b5c91c615506061f09bedd81a23babe3c","github/gh-aw-actions","--action-tag \"$PIN\"","contents: read","cmp --silent"])assert.ok(compile.includes(x),x);assert.doesNotMatch(compile,/contents:\s*write/);});
test("production firewall and live-proof stop gate remain documented",()=>{for(const x of ["Independent HIGH-risk QA PASS","No production League Vector behavior is changed","Issue #53","No PAT is introduced","Live proof — NOT AUTHORIZED"])assert.ok(docs.includes(x),x);});
