'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const p = require('../lib/development-automation/research-qa-protocol-v01');

const input = { repository:'kw7t9rwhny-cyber/league-vector', commit_sha:'a'.repeat(40), tree_sha:'b'.repeat(40) };
const forbidden = ['mutate_production','merge','install','deploy','release','change_authority','change_qa_criteria','dispatch_worker','remediate'];
function item(role='research') {
  return {
    schema_version:p.SCHEMA_VERSION,
    work_item_id:'phase3-pilot-0001', objective:'Audit workflow registry declarations against one immutable snapshot.', role, risk:'low',
    input_identity:{...input}, context_refs:[{kind:'public_file',ref:'.github/workflows/',immutable_identity:'a'.repeat(40),required:true}],
    allowed_actions: role==='research' ? ['read_repository','read_work_item','write_terminal_result'] : ['read_repository','read_work_item','read_upstream_result','write_terminal_result'],
    forbidden_actions:forbidden, expected_terminal_result:`${role}-terminal-result/v1`, qa_requirement:role==='research'?'one':'none', founder_gate:'founder-lead-stop-after-qa', confidentiality:'public',
    budget:{max_worker_runs:1,max_actions_runtime_minutes:10,max_ai_cost_or_credits:null}, replay_identity:'c'.repeat(64), dependencies:role==='qa'?['research-primary']:undefined,
  };
}
const actor={id:41898282,login:'github-actions[bot]',type:'Bot'};
const issuerIssue={user:{login:'founder',id:7,type:'User'}};
const permission={user:{login:'founder',id:7},permission:'admin'};
const substance=(role,status)=>({status,claims_or_findings:['finding'],evidence_refs:['repo:file'],artifact_refs:[],limitations:'',recommended_next_action:'Founder/Lead review.'});
function result(workItem, role, run=11, upstream=[]) {
  return p.buildTerminalResult({workItem,role,roleInstanceId:`${role}-primary`,workerRunId:run,runAttempt:1,upstreamResultIds:upstream,substance:substance(role,role==='qa'?'PASS':'COMPLETE'),createdAt:new Date().toISOString(),telemetry:{}});
}
const comment=(body,user=actor)=>({body,user});

test('validates minimum work item and trusted issuer',()=>{assert.equal(p.validateWorkItem(item()).ok,true);assert.equal(p.validateTrustedIssuer(issuerIssue,permission).ok,true);});
test('rejects model-capability authority expansion',()=>{const w=item();w.allowed_actions.push('merge');assert.equal(p.validateWorkItem(w).reason,'unauthorized_allowed_action');});
test('rejects missing founder stop',()=>{const w=item();w.founder_gate='auto-merge';assert.equal(p.validateWorkItem(w).reason,'invalid_founder_gate');});
test('public runtime rejects restricted work item',()=>{const w=item();w.confidentiality='restricted-rd';assert.equal(p.validateWorkItem(w).reason,'public_runtime_confidentiality_block');});
test('input SHA and tree are immutable identities',()=>{const w=item();w.input_identity.commit_sha='main';assert.equal(p.validateWorkItem(w).reason,'invalid_input_commit_sha');});
test('dispatch identity is deterministic and input-bound',()=>{const w=item();const a=p.computeDispatchIdentity({workItem:w,role:'research',roleInstanceId:'research-primary'});const b=p.computeDispatchIdentity({workItem:w,role:'research',roleInstanceId:'research-primary'});assert.equal(a,b);const w2=structuredClone(w);w2.input_identity.commit_sha='d'.repeat(40);assert.notEqual(a,p.computeDispatchIdentity({workItem:w2,role:'research',roleInstanceId:'research-primary'}));});
test('valid dispatch claim verifies',()=>{const w=item();const c=p.buildDispatchClaim({workItem:w,role:'research',roleInstanceId:'research-primary',createdAt:new Date().toISOString()});assert.equal(p.validateDispatchClaim(c,{workItem:w,role:'research',roleInstanceId:'research-primary',commentAuthor:actor}).ok,true);});
test('untrusted dispatch writer rejected',()=>{const w=item();const c=p.buildDispatchClaim({workItem:w,role:'research',roleInstanceId:'research-primary',createdAt:new Date().toISOString()});assert.equal(p.validateDispatchClaim(c,{workItem:w,role:'research',roleInstanceId:'research-primary',commentAuthor:{login:'user',type:'User'}}).reason,'untrusted_dispatch_claim_author');});
test('terminal result binds infrastructure provenance',()=>{const w=item();const r=result(w,'research');assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).ok,true);});
test('wrong work item rejected',()=>{const w=item();const r=result(w,'research');r.work_item_id='wrong-item';assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).reason,'wrong_work_item');});
test('wrong input identity rejected',()=>{const w=item();const r=result(w,'research');r.input_identity={...input,tree_sha:'d'.repeat(40)};assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).reason,'wrong_input_identity');});
test('wrong worker rejected',()=>{const w=item();const r=result(w,'research');r.worker_run_id=12;assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).reason,'wrong_worker_run');});
test('wrong role instance rejected',()=>{const w=item();const r=result(w,'research');r.role_instance_id='research-other';assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).reason,'wrong_role_instance');});
test('replayed run rejected',()=>{const w=item();const r=result(w,'research');r.run_attempt=2;assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).reason,'replayed_run');});
test('untrusted writer rejected',()=>{const w=item();const r=result(w,'research');assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:{login:'attacker',type:'User'}}).reason,'untrusted_comment_author');});
test('stale result rejected',()=>{const w=item();const r=p.buildTerminalResult({workItem:w,role:'research',roleInstanceId:'research-primary',workerRunId:11,runAttempt:1,substance:substance('research','COMPLETE'),createdAt:'2020-01-01T00:00:00Z',telemetry:{}});assert.equal(p.validateTerminalResult(r,{workItem:w,expectedRole:'research',expectedRoleInstanceId:'research-primary',expectedWorkerRunId:11,commentAuthor:actor}).reason,'stale_or_invalid_result_time');});
test('wrong upstream result rejected',()=>{const q=item('qa'),rr='d'.repeat(64);const r=result(q,'qa',22,[rr]);assert.equal(p.validateTerminalResult(r,{workItem:q,expectedRole:'qa',expectedRoleInstanceId:'qa-primary',expectedWorkerRunId:22,expectedUpstreamResultIds:['e'.repeat(64)],commentAuthor:actor}).reason,'wrong_upstream_result');});
test('QA PASS, FAIL, BLOCKED are structurally valid',()=>{for(const status of ['PASS','FAIL','BLOCKED']){const q=item('qa');const rr='d'.repeat(64);const r=p.buildTerminalResult({workItem:q,role:'qa',roleInstanceId:'qa-primary',workerRunId:22,runAttempt:1,upstreamResultIds:[rr],substance:substance('qa',status),createdAt:new Date().toISOString(),telemetry:{}});assert.equal(p.validateTerminalResult(r,{workItem:q,expectedRole:'qa',expectedRoleInstanceId:'qa-primary',expectedWorkerRunId:22,expectedUpstreamResultIds:[rr],commentAuthor:actor}).ok,true);}});
test('contradictory/unsupported QA verdict rejected',()=>{const q=item('qa');const rr='d'.repeat(64);const r=p.buildTerminalResult({workItem:q,role:'qa',roleInstanceId:'qa-primary',workerRunId:22,runAttempt:1,upstreamResultIds:[rr],substance:substance('qa','PASS'),createdAt:new Date().toISOString(),telemetry:{}});r.substance.status='COMPLETE';assert.equal(p.validateTerminalResult(r,{workItem:q,expectedRole:'qa',expectedRoleInstanceId:'qa-primary',expectedWorkerRunId:22,expectedUpstreamResultIds:[rr],commentAuthor:actor}).reason,'invalid_substance_status');});
test('zero terminal result fails durability proof',()=>{const w=item();assert.equal(p.authoritativeResultsFor({comments:[],workItem:w,role:'research',roleInstanceId:'research-primary',expectedWorkerRunId:11}).reason,'missing_terminal_result');});
test('duplicate terminal results fail durability proof',()=>{const w=item();const r=result(w,'research');const body=p.serializeMarkedJson(p.RESULT_MARKER,r);assert.equal(p.authoritativeResultsFor({comments:[comment(body),comment(body)],workItem:w,role:'research',roleInstanceId:'research-primary',expectedWorkerRunId:11}).reason,'duplicate_terminal_result');});
test('malformed current-run terminal family fails closed',()=>{const w=item();const body=`${p.RESULT_MARKER}\n{"work_item_id":"${w.work_item_id}","role":"research","role_instance_id":"research-primary"}`;assert.equal(p.authoritativeResultsFor({comments:[comment(body)],workItem:w,role:'research',roleInstanceId:'research-primary',expectedWorkerRunId:11}).reason,'malformed_authoritative_result_family');});
test('controller begins with research eligible',()=>{const r=item(),q=item('qa');assert.equal(p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[]}).state,'RESEARCH_ELIGIBLE');});
test('duplicate research wake-up is deduped by durable claim',()=>{const r=item(),q=item('qa');const c=p.buildDispatchClaim({workItem:r,role:'research',roleInstanceId:'research-primary',createdAt:new Date().toISOString()});assert.equal(p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.DISPATCH_MARKER,c))]}).state,'RESEARCH_DISPATCHED');});
test('valid Research result makes QA eligible',()=>{const r=item(),q=item('qa');const rr=result(r,'research');assert.equal(p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.RESULT_MARKER,rr))]}).state,'QA_ELIGIBLE');});
test('research FAIL/BLOCKED stops instead of dispatching QA',()=>{for(const status of ['FAIL','BLOCKED']){const r=item(),q=item('qa');const rr=p.buildTerminalResult({workItem:r,role:'research',roleInstanceId:'research-primary',workerRunId:11,runAttempt:1,substance:substance('research',status),createdAt:new Date().toISOString(),telemetry:{}});const s=p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.RESULT_MARKER,rr))]});assert.equal(s.state,'FOUNDER_STOP');assert.equal(s.terminalDisposition,status);}});
test('QA PASS closes at Founder stop',()=>{const r=item(),q=item('qa');const rr=result(r,'research');const qr=p.buildTerminalResult({workItem:q,role:'qa',roleInstanceId:'qa-primary',workerRunId:22,runAttempt:1,upstreamResultIds:[rr.result_id],substance:substance('qa','PASS'),createdAt:new Date().toISOString(),telemetry:{}});const s=p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.RESULT_MARKER,rr)),comment(p.serializeMarkedJson(p.RESULT_MARKER,qr))]});assert.equal(s.state,'FOUNDER_STOP');assert.equal(s.terminalDisposition,'PASS');});
test('QA FAIL closes at Founder stop without remediation',()=>{const r=item(),q=item('qa');const rr=result(r,'research');const qr=p.buildTerminalResult({workItem:q,role:'qa',roleInstanceId:'qa-primary',workerRunId:22,runAttempt:1,upstreamResultIds:[rr.result_id],substance:substance('qa','FAIL'),createdAt:new Date().toISOString(),telemetry:{}});const s=p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.RESULT_MARKER,rr)),comment(p.serializeMarkedJson(p.RESULT_MARKER,qr))]});assert.equal(s.state,'FOUNDER_STOP');assert.equal(s.terminalDisposition,'FAIL');});
test('QA BLOCKED closes at Founder stop and is not PASS',()=>{const r=item(),q=item('qa');const rr=result(r,'research');const qr=p.buildTerminalResult({workItem:q,role:'qa',roleInstanceId:'qa-primary',workerRunId:22,runAttempt:1,upstreamResultIds:[rr.result_id],substance:substance('qa','BLOCKED'),createdAt:new Date().toISOString(),telemetry:{}});const s=p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.RESULT_MARKER,rr)),comment(p.serializeMarkedJson(p.RESULT_MARKER,qr))]});assert.equal(s.terminalDisposition,'BLOCKED');assert.notEqual(s.terminalDisposition,'PASS');});
test('duplicate QA result cannot create green completion',()=>{const r=item(),q=item('qa');const rr=result(r,'research');const qr=p.buildTerminalResult({workItem:q,role:'qa',roleInstanceId:'qa-primary',workerRunId:22,runAttempt:1,upstreamResultIds:[rr.result_id],substance:substance('qa','PASS'),createdAt:new Date().toISOString(),telemetry:{}});const body=p.serializeMarkedJson(p.RESULT_MARKER,qr);assert.equal(p.assessControllerState({researchWorkItem:r,qaWorkItem:q,comments:[comment(p.serializeMarkedJson(p.RESULT_MARKER,rr)),comment(body),comment(body)]}).reason,'duplicate_protocol_record');});
test('budget exhaustion blocks another worker run',()=>{const w=item();const c=p.buildDispatchClaim({workItem:w,role:'research',roleInstanceId:'research-primary',createdAt:new Date().toISOString()});assert.equal(p.enforceRunBudget({workItem:w,comments:[comment(p.serializeMarkedJson(p.DISPATCH_MARKER,c))],roleInstanceId:'research-primary'}).reason,'run_limit_exhausted');});
test('malformed dispatch family fails budget/replay checks closed',()=>{const w=item();assert.equal(p.enforceRunBudget({workItem:w,comments:[comment(`${p.DISPATCH_MARKER}\nnot-json`)],roleInstanceId:'research-primary'}).reason,'malformed_dispatch_claim_family');});
test('telemetry captures bounded machine-readable timing fields',()=>{const t=p.makeTelemetry({workflowCreatedAt:'2026-08-18T10:00:00Z',runStartedAt:'2026-08-18T10:00:02Z',terminalAt:'2026-08-18T10:00:10Z'});assert.equal(t.queue_wait_ms,2000);assert.equal(t.wall_time_ms,8000);assert.equal(t.ai_cost_or_credits,null);});
test('work-item marker parser rejects prose/duplicate envelope lines',()=>{const w=item();const body=p.serializeMarkedJson(p.WORK_ITEM_MARKER,w);assert.equal(p.parseWorkItemIssue({body}).ok,true);assert.equal(p.parseWorkItemIssue({body:body+'\nextra'}).ok,false);});
test('false-green worker completion is impossible without singleton durable result',()=>{const w=item();const r=result(w,'research');const valid=comment(p.serializeMarkedJson(p.RESULT_MARKER,r));assert.equal(p.authoritativeResultsFor({comments:[valid],workItem:w,role:'research',roleInstanceId:'research-primary',expectedWorkerRunId:11}).ok,true);assert.equal(p.authoritativeResultsFor({comments:[],workItem:w,role:'research',roleInstanceId:'research-primary',expectedWorkerRunId:11}).ok,false);});
test('derived QA work item preserves immutable input and founder stop',()=>{const r=item();const q=p.deriveQaWorkItem(r);assert.equal(q.role,'qa');assert.deepEqual(q.input_identity,r.input_identity);assert.equal(q.qa_requirement,'none');assert.equal(q.founder_gate,'founder-lead-stop-after-qa');});
test('worker run metadata binds production workflow path and successful attempt 1',()=>{const run={id:77,event:'workflow_dispatch',path:'.github/workflows/development-research-worker-v01.yml',run_attempt:1,status:'completed',conclusion:'success'};assert.equal(p.validateWorkerRunMetadata(run,{role:'research',expectedRunId:77}).ok,true);for(const [key,value] of [['event','push'],['path','.github/workflows/other.yml'],['run_attempt',2],['conclusion','failure']]){const bad={...run,[key]:value};assert.equal(p.validateWorkerRunMetadata(bad,{role:'research',expectedRunId:77}).ok,false);}});
