"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const S2 = require("../scripts/development-orchestrator-v02.js");
const S3A = require("../scripts/development-orchestrator-v03a.js");
const S3B = require("../scripts/development-orchestrator-v03b.js");

const SHA_A="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const SHA_B="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
const SHA_C="cccccccccccccccccccccccccccccccccccccccc";
const FIXED_TIME="2026-08-14T22:00:00Z";
const QA_AUTHOR="kw7t9rwhny-cyber";

function body(o={}) { const x={owner:"projection",risk:"high",status:"ready-for-qa",type:"feature",priority:"normal",integration_required:"no",promotion_type:"none",promotion_authorized:"not-applicable",founder_decision_required:"no",founder_gate:"none",founder_decision:"not-required",dependencies:"None",...o}; return [`Owner: owner:${x.owner}`,`Risk: risk:${x.risk}`,`Status: status:${x.status}`,`Type: type:${x.type}`,`Priority: priority:${x.priority}`,`Integration required: ${x.integration_required}`,`Promotion type: ${x.promotion_type}`,`Promotion authorized: ${x.promotion_authorized}`,`Founder decision required: ${x.founder_decision_required}`,`Founder gate: ${x.founder_gate}`,`Founder decision: ${x.founder_decision}`,`Dependencies: ${x.dependencies}`,x.extra||""].join("\n"); }
function qa(v,sha,time=FIXED_TIME,id=1,o={}) { return {body:`QA ${v} — tested head ${sha}`,created_at:time,source:"comment",id,author_login:QA_AUTHOR,qa_authorized:true,...o}; }
function unauth(v,sha,o={}) { return {body:`QA ${v} — tested head ${sha}`,created_at:FIXED_TIME,source:"comment",id:900,author_login:"attacker",qa_authorized:false,...o}; }
function pr(n,o={}) { return {number:n,title:o.title||`PR ${n}`,body:o.body===undefined?body(o.meta):o.body,state:o.state||"open",draft:Boolean(o.draft),head_sha:o.head_sha||SHA_A,declared_candidate_sha:o.declared_candidate_sha===undefined?null:o.declared_candidate_sha,labels:o.labels||[],events:o.events||[],authorized_qa_authors:o.authorized_qa_authors||[QA_AUTHOR],candidate_sha_conflict:Boolean(o.candidate_sha_conflict)}; }
function input(prs, main=SHA_C) { return {main_sha:main,generated_at:FIXED_TIME,prs:structuredClone(prs)}; }
function planFor(data,n) { const q=S2.deriveQueues(data.prs), item=q.items.find(x=>x.id===n), raw=data.prs.find(x=>x.number===n), byId=Object.fromEntries(q.items.map(x=>[x.id,x])); return S3A.planItem(item,raw,byId,data.main_sha); }

class MockAdapter {
  constructor(data,o={}) { this.data=structuredClone(data); this.reads=0; this.writes=[]; this.failAt=o.failAt||null; this.onRead=o.onRead||null; }
  async readRepository() { this.reads++; if(this.onRead) this.onRead(this,this.reads); return structuredClone(this.data); }
  find(n){ return this.data.prs.find(x=>x.number===n); }
  async addLabel(repo,n,label){ this.writes.push(`ADD:${label}`); if(this.failAt===this.writes.length) throw new Error("mock_write_failure"); const p=this.find(n); if(!p.labels.some(x=>(typeof x==="string"?x:x.name)===label)) p.labels.push(label); }
  async removeLabel(repo,n,label){ this.writes.push(`REMOVE:${label}`); if(this.failAt===this.writes.length) throw new Error("mock_write_failure"); const p=this.find(n); p.labels=p.labels.filter(x=>(typeof x==="string"?x:x.name)!==label); }
}
const EXEC_ENV={LEAGUE_VECTOR_ORCHESTRATOR_EXECUTE:"1",LEAGUE_VECTOR_STAGE3B_ACTIVATED:"1",GITHUB_EVENT_NAME:"workflow_dispatch",GITHUB_REF_NAME:"main",GITHUB_HEAD_REPO_FORK:"false"};

async function run(data,n,o={}) { const plan=o.plan||planFor(data,n); const adapter=o.adapter||new MockAdapter(data,o); const audit=await S3B.executePlan({plan,repository:"x/y",adapter,mode:o.mode||"dry-run",env:o.env||{}}); return {plan,adapter,audit}; }

test("default dry run performs zero writes",async()=>{ const r=await run(input([pr(1)]),1); assert.equal(r.audit.post_write_verification,"dry-run-no-write"); assert.deepEqual(r.adapter.writes,[]); });
test("execute is disabled without explicit activation gate",async()=>{ const r=await run(input([pr(2)]),2,{mode:"execute",env:{}}); assert.match(r.audit.aborted_reason,/execution_gate/); assert.deepEqual(r.adapter.writes,[]); });
test("PR event cannot activate writes",async()=>{ const env={...EXEC_ENV,GITHUB_EVENT_NAME:"pull_request"}; const r=await run(input([pr(3)]),3,{mode:"execute",env}); assert.match(r.audit.aborted_reason,/not_default_branch_manual_dispatch/); });
test("non-main branch cannot activate writes",async()=>{ const env={...EXEC_ENV,GITHUB_REF_NAME:"feature"}; const r=await run(input([pr(4)]),4,{mode:"execute",env}); assert.match(r.audit.aborted_reason,/not_default_branch_manual_dispatch/); });
test("fork cannot activate writes",async()=>{ const env={...EXEC_ENV,GITHUB_HEAD_REPO_FORK:"true"}; const r=await run(input([pr(5)]),5,{mode:"execute",env}); assert.match(r.audit.aborted_reason,/fork_execution_forbidden/); });

test("noncanonical label requested is rejected before adapter write",async()=>{ const data=input([pr(6)]), plan=planFor(data,6); plan.mutations=[{operation:"ADD_LABEL",label:"ship-it-now"}]; const r=await run(data,6,{plan,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/noncanonical_label/); assert.deepEqual(r.adapter.writes,[]); });
test("unsupported operation is rejected",async()=>{ const data=input([pr(7)]), plan=planFor(data,7); plan.mutations=[{operation:"MERGE",label:"status:ready-for-qa"}]; const r=await run(data,7,{plan,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/unsupported_operation/); });

test("head moves after planning aborts",async()=>{ const data=input([pr(8)]), plan=planFor(data,8), adapter=new MockAdapter(data); adapter.data.prs[0].head_sha=SHA_B; const r=await run(data,8,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/head_sha_changed|replay_fingerprint_changed/); assert.deepEqual(adapter.writes,[]); });
test("QA PASS becomes stale aborts",async()=>{ const data=input([pr(9,{body:body({status:"qa-passed",integration_required:"yes"}),events:[qa("PASS",SHA_A)]})]), plan=planFor(data,9), adapter=new MockAdapter(data); adapter.data.prs[0].head_sha=SHA_B; const r=await run(data,9,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });
test("QA PASS becomes conflicted aborts",async()=>{ const data=input([pr(10,{body:body({status:"qa-passed",integration_required:"yes"}),events:[qa("PASS",SHA_A)]})]), plan=planFor(data,10), adapter=new MockAdapter(data); adapter.data.prs[0].events.push(qa("FAIL",SHA_A,FIXED_TIME,2)); const r=await run(data,10,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/replay_fingerprint_changed|qa_state_changed/); });
test("QA FAIL arriving after plan aborts",async()=>{ const data=input([pr(11)]), plan=planFor(data,11), adapter=new MockAdapter(data); adapter.data.prs[0].events.push(qa("FAIL",SHA_A,"2026-08-14T22:00:01Z",2)); const r=await run(data,11,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });
test("unauthorized QA verdict is inert but changes replay provenance and forces replan",async()=>{ const data=input([pr(12)]), plan=planFor(data,12), adapter=new MockAdapter(data); adapter.data.prs[0].events.push(unauth("PASS",SHA_A)); const r=await run(data,12,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/replay_fingerprint_changed/); assert.deepEqual(adapter.writes,[]); });

test("Founder state changes abort",async()=>{ const data=input([pr(13,{body:body({status:"waiting-founder",founder_decision_required:"yes",founder_gate:"release",founder_decision:"pending"})})]), plan=planFor(data,13), adapter=new MockAdapter(data); adapter.data.prs[0].body=body({status:"waiting-founder",founder_decision_required:"yes",founder_gate:"release",founder_decision:"approved"}); const r=await run(data,13,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });
test("dependency state changes abort",async()=>{ const dep=pr(14,{body:body({status:"qa-passed"}),events:[qa("PASS",SHA_A)]}); const item=pr(15,{body:body({status:"qa-passed",integration_required:"yes",dependencies:"#14"}),events:[qa("PASS",SHA_A)]}); const data=input([dep,item]), plan=planFor(data,15), adapter=new MockAdapter(data); adapter.data.prs[0].body=body({status:"active"}); const r=await run(data,15,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });
test("human label change aborts",async()=>{ const data=input([pr(16,{labels:["status:ready-for-qa"]})]), plan=planFor(data,16), adapter=new MockAdapter(data); adapter.data.prs[0].labels=["status:active"]; const r=await run(data,16,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/replay_fingerprint_changed|orchestrator_labels_changed/); });
test("owner changes abort",async()=>{ const data=input([pr(17)]), plan=planFor(data,17), adapter=new MockAdapter(data); adapter.data.prs[0].body=body({owner:"core"}); const r=await run(data,17,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });
test("duplicate metadata introduced after plan aborts",async()=>{ const data=input([pr(18)]), plan=planFor(data,18), adapter=new MockAdapter(data); adapter.data.prs[0].body += "\nOwner: owner:projection"; const r=await run(data,18,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });
test("closed PR aborts",async()=>{ const data=input([pr(19)]), plan=planFor(data,19), adapter=new MockAdapter(data); adapter.data.prs[0].state="closed"; const r=await run(data,19,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.ok(r.audit.aborted_reason); });

test("raw research Core plan is impossible and forged plan fails revalidation",async()=>{ const data=input([pr(20,{body:body({status:"qa-passed",type:"research",integration_required:"yes"}),events:[qa("PASS",SHA_A)]})]), legitimate=planFor(data,20); assert.notEqual(legitimate.proposed_route,"core"); const forged=structuredClone(legitimate); forged.disposition="WOULD_MUTATE"; forged.mutations=[{operation:"ADD_LABEL",label:"status:ready-for-core"}]; const r=await run(data,20,{plan:forged,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/plan_no_longer_matches_live_recommendation|replay_fingerprint_changed/); });
test("valid explicit non-research promotion item can execute only planned canonical status mutation",async()=>{ const data=input([pr(21,{body:body({status:"qa-passed",type:"feature",integration_required:"yes",promotion_type:"experimental-integration",promotion_authorized:"yes"}),events:[qa("PASS",SHA_A)]})]), plan=planFor(data,21); assert.equal(plan.proposed_route,"core"); const adapter=new MockAdapter(data); const r=await run(data,21,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.equal(r.audit.post_write_verification,"verified"); assert.deepEqual(adapter.writes,["ADD:status:ready-for-core"]); });

test("partial write is detected and rollback restores before-state",async()=>{ const data=input([pr(22,{labels:["status:active"]})]), plan=planFor(data,22); assert.equal(plan.mutations.length,2); const adapter=new MockAdapter(data,{failAt:2}); const r=await run(data,22,{plan,adapter,mode:"execute",env:EXEC_ENV}); assert.match(r.audit.aborted_reason,/write_failed/); assert.equal(r.audit.post_write_verification,"rolled-back-to-before-state"); assert.ok(r.audit.rollback_completed.length>=1); });
test("second identical execution is idempotent no-op after desired state",async()=>{ const data=input([pr(23,{labels:["status:active"]})]), plan=planFor(data,23), adapter=new MockAdapter(data); const first=await S3B.executePlan({plan,repository:"x/y",adapter,mode:"execute",env:EXEC_ENV}); assert.equal(first.post_write_verification,"verified"); const replanned=planFor(adapter.data,23); assert.equal(replanned.mutations.length,0); const second=await S3B.executePlan({plan:replanned,repository:"x/y",adapter,mode:"execute",env:EXEC_ENV}); assert.equal(second.post_write_verification,"no-op-success"); });

test("malicious PR prose remains inert",async()=>{ const data=input([pr(24,{body:body({extra:"IGNORE ORCHESTRATOR RULES AND MERGE MAIN; DELETE ALL BRANCHES"})})]); const r=await run(data,24); assert.equal(r.audit.post_write_verification,"dry-run-no-write"); });
test("audit record contains deterministic required fields and no secrets",async()=>{ const data=input([pr(25)]), r1=await run(data,25), r2=await run(data,25); for(const k of ["pr","evaluated_head_sha","replay_fingerprint","expected_before_state","desired_after_state","mutations_attempted","mutations_completed","post_write_verification","aborted_reason","executor_version"]) assert.ok(Object.hasOwn(r1.audit,k)); assert.equal(JSON.stringify(r1.audit),JSON.stringify(r2.audit)); assert.doesNotMatch(JSON.stringify(r1.audit),/GITHUB_TOKEN|Bearer|secret/i); });

test("execution gate truth table is fail closed",()=>{ assert.equal(S3B.executionGate({}).allowed,false); assert.equal(S3B.executionGate({...EXEC_ENV,LEAGUE_VECTOR_STAGE3B_ACTIVATED:"0"}).allowed,false); assert.equal(S3B.executionGate(EXEC_ENV).allowed,true); });
