"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const root=path.resolve(__dirname,".."),read=p=>fs.readFileSync(path.join(root,p),"utf8");
const research=read(".github/workflows/stage3c-research-worker.md"),qa=read(".github/workflows/stage3c-qa-worker.md"),compile=read(".github/workflows/stage3c-agentic-compile-validation.yml"),docs=read("docs/development-orchestrator-stage3c-two-worker-proof-v01.md"),locks=[read(".github/workflows/stage3c-research-worker.lock.yml"),read(".github/workflows/stage3c-qa-worker.lock.yml")];
const repo="kw7t9rwhny-cyber/league-vector",marker="STAGE3C_RESEARCH_ACTIVATION_CLAIM v0.1",bot={id:41898282,login:"github-actions[bot]",type:"Bot"};
const dormant="Fixture revision: stage3c-v0.1-r1\n\nEligibility: DORMANT\n",ready="Fixture revision: stage3c-v0.1-r1\n\nEligibility: READY\n";
const sha=v=>crypto.createHash("sha256").update(v,"utf8").digest("hex");
function eligible({repoName=repo,issue=53,title="AGENT SPIKE TEST — harmless two-worker handoff",before,after,attempt="1"}){const val=b=>{if(typeof b!=="string")return null;const m=[...b.matchAll(/^Eligibility: ([^\r\n]+)$/gm)];return m.length===1?m[0][1]:null},rev=b=>typeof b==="string"?[...b.matchAll(/^Fixture revision: stage3c-v0\.1-r1$/gm)].length:0;if(repoName!==repo||issue!==53||title!=="AGENT SPIKE TEST — harmless two-worker handoff"||attempt!=="1"||typeof before!=="string"||typeof after!=="string"||rev(before)!==1||rev(after)!==1||val(before)!=="DORMANT"||val(after)!=="READY")return false;return after===before.replace(/^Eligibility: DORMANT$/m,"Eligibility: READY")}
function activationIdentity({repoName=repo,issue=53,revision="stage3c-v0.1-r1",before=dormant,after=ready,updatedAt="2026-08-17T03:00:00Z"}={}){return sha(JSON.stringify({repository:repoName,fixture_issue:issue,fixture_revision:revision,transition:"DORMANT->READY",previous_body_sha256:sha(before),current_body_sha256:sha(after),issue_updated_at:updatedAt}))}
function canonicalClaim({id=activationIdentity(),repository=repo,issue=53,revision="stage3c-v0.1-r1",transition="DORMANT->READY",runId=7001,runNumber=91,status="claimed"}={}){return [marker,`repository: ${repository}`,`fixture_issue: ${issue}`,`fixture_revision: ${revision}`,`transition: ${transition}`,`activation_id: ${id}`,`research_run_id: ${runId}`,`research_run_number: ${runNumber}`,`claim_status: ${status}`].join("\n")}
function comment(body,user=bot){return {user,body}}
function parseCanonical(body){if(typeof body!=="string"||body.includes("\r"))return null;const lines=body.split("\n");if(lines.length!==9||lines[0]!==marker)return null;const ps=[/^repository: ([A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)$/,/^fixture_issue: ([1-9][0-9]*)$/,/^fixture_revision: (stage3c-v0\.1-r[1-9][0-9]*)$/,/^transition: (DORMANT->READY)$/,/^activation_id: ([a-f0-9]{64})$/,/^research_run_id: ([1-9][0-9]*)$/,/^research_run_number: ([1-9][0-9]*)$/,/^claim_status: (claimed)$/],v=[];for(let i=0;i<ps.length;i++){const m=lines[i+1].match(ps[i]);if(!m)return null;v.push(m[1])}return{repository:v[0],fixtureIssue:Number(v[1]),fixtureRevision:v[2],transition:v[3],activationId:v[4],researchRunId:Number(v[5]),researchRunNumber:Number(v[6]),claimStatus:v[7]}}
function resolveClaims({claims=[],id=activationIdentity(),revision="stage3c-v0.1-r1"}={}){const same=[];for(const c of claims){const trusted=c.user?.id===bot.id&&c.user?.login===bot.login&&c.user?.type===bot.type;if(!trusted)continue;if(typeof c.body!=="string")continue;const markers=c.body.split("\n").filter(l=>l===marker).length;if(markers===0)continue;if(markers!==1)return{codexReachable:false,reason:"ambiguity:duplicate_marker"};const p=parseCanonical(c.body);if(!p)return{codexReachable:false,reason:"ambiguity:malformed"};if(p.activationId!==id)continue;if(p.repository!==repo||p.fixtureIssue!==53||p.fixtureRevision!==revision||p.transition!=="DORMANT->READY"||p.claimStatus!=="claimed")return{codexReachable:false,reason:"ambiguity:conflict"};same.push(p)}if(same.length>1)return{codexReachable:false,reason:"ambiguity:multiple"};if(same.length===1)return{codexReachable:false,reason:"already_claimed"};return{codexReachable:true,reason:"claim_may_be_created"}}
function activationGate({before=dormant,after=ready,attempt="1",eventUpdatedAt="2026-08-17T03:00:00Z",currentUpdatedAt=eventUpdatedAt,currentBody=after,claims=[]}={}){if(!eligible({before,after,attempt}))return{codexReachable:false,reason:"transition"};if(typeof eventUpdatedAt!=="string"||!Number.isFinite(Date.parse(eventUpdatedAt)))return{codexReachable:false,reason:"identity"};const id=activationIdentity({before,after,updatedAt:eventUpdatedAt});const claimState=resolveClaims({claims,id});if(!claimState.codexReachable)return claimState;if(currentBody!==after||currentUpdatedAt!==eventUpdatedAt)return{codexReachable:false,reason:"stale"};return claimState}
function job(lock,name){const mk=`\n  ${name}:\n`,i=lock.indexOf(mk);assert.notEqual(i,-1);const rest=lock.slice(i+mk.length),m=rest.match(/\n  [A-Za-z0-9_-]+:\n/);return m?rest.slice(0,m.index):rest}

test("Worker A exact transition remains fail closed",()=>{assert.equal(eligible({before:dormant,after:ready}),true);for(const a of [{before:ready,after:ready},{before:dormant.replace("DORMANT","UNKNOWN"),after:ready},{before:undefined,after:ready},{before:dormant,after:undefined},{before:dormant,after:ready.replace("READY","ready")},{before:dormant,after:ready+"extra\n"},{before:dormant,after:ready,issue:54},{before:dormant,after:ready,repoName:"attacker/repo"},{before:dormant,after:ready,attempt:"2"}])assert.equal(eligible(a),false)});

test("Worker A activation claim ambiguity matrix makes Codex unreachable for every ambiguous state",()=>{const id=activationIdentity(),valid=comment(canonicalClaim({id}));assert.equal(resolveClaims().codexReachable,true,"1 zero prior claim");assert.equal(resolveClaims({claims:[valid],id}).codexReachable,false,"2 exactly one valid claim blocks replay");assert.match(resolveClaims({claims:[valid,valid],id}).reason,/ambiguity/,"3 duplicate valid claims fail closed");assert.match(resolveClaims({claims:[valid,comment(canonicalClaim({id,revision:"stage3c-v0.1-r2"}))],id}).reason,/ambiguity/,"4 conflicting same-id claims fail closed");assert.match(resolveClaims({claims:[valid,comment(canonicalClaim({id})+"\nclaim_status: broken")],id}).reason,/ambiguity/,"5 valid plus malformed trusted claim fails closed");const forged=comment(canonicalClaim({id}),{id:316007980,login:"kw7t9rwhny-cyber",type:"User"});assert.equal(resolveClaims({claims:[forged],id}).codexReachable,true,"6 user-forged prose has no authority");const botLooking=comment(canonicalClaim({id}),{id:999999,login:"github-actions[bot]",type:"Bot"});assert.equal(resolveClaims({claims:[botLooking],id}).codexReachable,true,"7 bot-looking string without stable actor id has no authority");assert.equal(resolveClaims({claims:[comment(`note ${marker} not authority`)],id}).codexReachable,true,"8 embedded marker is not authority");assert.match(resolveClaims({claims:[comment(canonicalClaim({id})+`\n${marker}`)],id}).reason,/ambiguity/,"9 duplicate markers fail closed");const staleId=activationIdentity({updatedAt:"2026-08-17T02:00:00Z"});assert.equal(resolveClaims({claims:[comment(canonicalClaim({id:staleId}))],id}).codexReachable,true,"10 stale prior activation has no current authority");const r2Id=activationIdentity({revision:"stage3c-v0.1-r2"});assert.equal(resolveClaims({claims:[comment(canonicalClaim({id:r2Id,revision:"stage3c-v0.1-r2"}))],id}).codexReachable,true,"11 different revision claim has no current authority");assert.match(resolveClaims({claims:[comment(canonicalClaim({id,runId:"broken"}))],id}).reason,/ambiguity/,"12 inconsistent correlation metadata fails closed");assert.match(resolveClaims({claims:[comment(`${marker}\nrepository: ${repo}\nactivation_id: ${id}`)],id}).reason,/ambiguity/,"13 valid hash with truncated schema fails closed");assert.match(resolveClaims({claims:[comment(canonicalClaim({id}).replace("repository: ","repository:  "))],id}).reason,/ambiguity/,"14 noncanonical whitespace fails closed");assert.equal(activationGate({claims:[valid]}).codexReachable,false,"15 sequential duplicate after completed Research remains blocked")});

test("same-activation race is serialized and second start observes durable claim",()=>{const id=activationIdentity();const x=resolveClaims({claims:[],id});assert.equal(x.codexReachable,true);const durable=[comment(canonicalClaim({id,runId:7001,runNumber:91}))];const y=resolveClaims({claims:durable,id});assert.equal(y.codexReachable,false);for(const s of ["stage3c-research-fixture-53","cancel-in-progress: false","activation_claim_ambiguity:multiple_same_activation_claims","actionsBot = Object.freeze({ id: 41898282","parseCanonicalClaim","sameActivationClaims.length > 1"])assert.ok(research.includes(s),s);assert.ok(research.indexOf("sameActivationClaims.length > 1")<research.indexOf("github.rest.issues.createComment"));assert.ok(research.includes("needs.pre_activation.outputs.exact_transition_result == 'success'"))});

test("Worker B authority and independence are preserved",()=>{for(const x of ["wr.name !== 'Stage 3C Research Worker A'","wr.path !== '.github/workflows/stage3c-research-worker.lock.yml'","wr.event !== 'issues'","wr.head_branch !== 'main'","wr.conclusion !== 'success'","wr.run_attempt !== 1","researchForRun.length !== 1","github-actions[bot]","research_result_outside_authoritative_window","prior_authoritative_qa_result","needs.pre_activation.outputs.research_authority_result == 'success'"])assert.ok(qa.includes(x),x);assert.doesNotMatch(qa,/dispatch-workflow|call-workflow/)});

test("generated executable Worker A pre-activation enforces strict claim authority before agent",()=>{const pre=job(locks[0],"pre_activation");for(const x of ["issues: write","41898282","parseCanonicalClaim","activation_claim_ambiguity:duplicate_marker","activation_claim_ambiguity:malformed_canonical_claim","activation_claim_ambiguity:conflicting_same_activation_metadata","activation_claim_ambiguity:multiple_same_activation_claims","activation_already_claimed","createComment"])assert.ok(pre.includes(x),x);assert.doesNotMatch(pre,/contents: write|pull-requests: write|actions: write/);const agent=job(locks[0],"agent");assert.ok(agent.includes("contents: read")&&agent.includes("issues: read")&&agent.includes("GITHUB_READ_ONLY"));assert.doesNotMatch(agent,/:\s*write/)});

test("generated permissions, safe outputs, secret boundary, determinism and production firewall remain unchanged",()=>{for(const lock of locks){const agent=job(lock,"agent"),safe=job(lock,"safe_outputs");assert.ok(agent.includes("contents: read")&&agent.includes("issues: read")&&agent.includes("GITHUB_READ_ONLY"));assert.doesNotMatch(agent,/:\s*write/);assert.ok(safe.includes("issues: write"));assert.doesNotMatch(safe,/contents: write|pull-requests: write|actions: write/);for(const x of ["contents: write","pull-requests: write","actions: write","deployments: write","packages: write","administration: write","statuses: write","checks: write"])assert.ok(!lock.includes(x),x);const m=lock.match(/GH_AW_SAFE_OUTPUTS_HANDLER_CONFIG: "[^\n]+"/);assert.ok(m);for(const x of ["add_comment","target\\\":\\\"53","max\\\":1","report_incomplete"])assert.ok(m[0].includes(x),x);for(const x of ['"OPENAI_API_KEY"','"agent_id":"codex"','"compiler_version":"v0.86.2"','"strict":true'])assert.ok(lock.includes(x),x)}for(const s of [research,qa,compile])assert.doesNotMatch(s,/OPENAI_API_KEY|CODEX_API_KEY|github_pat_|gh[pousr]_/i);for(const x of ["v0.86.2/linux-amd64","b8fd100d1d56a77b842ad28375ff361215a5aa1277db6b9a05d70054cde7260e","6aab9e5b5c91c615506061f09bedd81a23babe3c","github/gh-aw-actions","--action-tag \"$PIN\"","permissions:\n  contents: read","cmp --silent"])assert.ok(compile.includes(x),x);for(const x of ["Independent HIGH-risk QA PASS","No production League Vector behavior is changed","Issue #53","No PAT is introduced","Live proof — NOT AUTHORIZED"])assert.ok(docs.includes(x),x)});
