const test=require('node:test');const assert=require('node:assert/strict');const Core=require('../core-v08.js');const F=require('../idp-valuation-foundation-v01.js');
const league={total_rosters:14,roster_positions:['QB','RB','WR','TE','DL','DL','LB','DB','IDP_FLEX','BN']};

test('IDP numeric dynasty value remains unavailable',()=>{const projection={identity:{sleeper_id:'idp1'},position:'LB',projected_stats:{solo_tackles:80,sacks:4},supported_stat_keys:['solo_tackles','sacks'],model:{name:'research-idp',version:'r1',research_approved:true}};const scoring=F.scoreProjection(projection,{tkl_solo:1.5,sack:4});const replacement=F.replacementRequest({league,position:'LB',methodology:{name:'walk-forward-vorp',version:'r1',research_approved:true}});const ageCurve=F.ageCurveHook({position:'LB',age:26,curve:{version:'r1',research_approved:true,parameters:[{age:26,effect:0}]}});const normalization=F.normalizationHook({name:'surplus-z',version:'r1',research_approved:true});const state=F.candidateDynastyState({projection,scoring,replacement,ageCurve,normalization});assert.equal(state.idp_dynasty_value_available,false);assert.equal(state.dynasty_value,null);assert.equal(state.combined_ranking_available,false);assert.equal(state.reason,'production_firewall_closed');});

test('partial scoring coverage stays explicit',()=>{const result=F.scoreProjection({identity:{sleeper_id:'idp2'},position:'DE',projected_stats:{sacks:10},supported_stat_keys:['sacks'],model:{name:'research-idp',version:'r1'}},{sack:4,tkl_solo:1.5,idp_custom_pressure:2});assert.equal(result.completeness,'partial');assert.equal(result.scoring_claim,'explicitly_incomplete');assert.ok(result.missing_stat_keys.includes('solo_tackles'));assert.ok(result.unsupported_keys.includes('idp_custom_pressure'));assert.equal(result.applied_to_dynasty_value,false);});

test('lineup demand recognizes position-specific starters and shared flex without triple counting',()=>{const d=F.lineupDemand(league);assert.equal(d.positions.DL.dedicated_league_starters,28);assert.equal(d.positions.LB.dedicated_league_starters,14);assert.equal(d.positions.DB.dedicated_league_starters,14);assert.equal(d.shared_idp_flex_league_slots,14);for(const p of ['DL','LB','DB'])assert.equal(d.positions[p].shared_flex_allocation,'unallocated');});

test('replacement and scarcity stay separate',()=>{const replacement=F.replacementRequest({league,position:'DL'}),scarcity=F.scarcityContext({league,position:'DL'});assert.equal(replacement.status,'methodology_unavailable');assert.equal(replacement.replacement_points,null);assert.equal(replacement.applied_to_dynasty_value,false);assert.equal(scarcity.replacement_component_included,false);assert.equal(scarcity.scarcity_adjustment,null);});

test('team totals remain incomplete when IDP values are unavailable',()=>{const state=F.teamTotalsCompleteness({idp_player_count:17,offensive_match_completeness:96});assert.equal(state.numeric_scope,'offense_only');assert.equal(state.idp_numeric_values_available,false);assert.equal(state.overall_numeric_total_complete,false);assert.equal(state.warning_required,true);});

test('age and normalization hooks invent no numeric adjustment',()=>{assert.equal(F.ageCurveHook({position:'DB',age:29}).adjustment,null);assert.equal(F.normalizationHook().normalized_surplus,null);});

test('offensive dynasty outputs are unchanged',()=>{const input={player:{position:'RB',years_exp:4},market:{base:6000,age:26,ecr:18,format:'1qb'},context:{values:{RB:{structuralScore:107}}},projection:{points:220},neutralReplacement:{levels:{RB:120}},leagueReplacement:{levels:{RB:130}},tradeCount:2};const before=Core.calculateValuation(input);F.lineupDemand(league);const after=Core.calculateValuation(input);assert.deepEqual(after,before);});
