const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const PF=require('../projection-frontend-v03.js');const Core=require('../core-v08.js');
function rec(position,stats){return{sleeper_id:'1',gsis_id:'g1',position,projection_status:'projection_ready',projected_stats:stats,confidence:'High',history_seasons:[2025,2024],experimental:true,production_projection_eligible:false,dynasty_value_eligible:false};}
test('compact projection artifacts normalize and join by Sleeper ID',()=>{const a=PF.buildIndex({v:'x',m:'m',d:'2026-08-13T00:00:00Z',through:2025,r:[{s:'1',g:'g1',p:'WR',z:'projection_ready',x:{rc:80,cy:1000,ct:8},c:'High',h:[2025]}]});const rows=PF.joinLeaguePlayers(['1'],{'1':{full_name:'Example',position:'WR',team:'GB'}},a,{rec:1,rec_yd:.1,rec_td:6});assert.equal(rows[0].name,'Example');assert.equal(rows[0].scoring.points,228);assert.equal(rows[0].projected_position_rank,'WR1');});
test('same football projection changes with league scoring',()=>{const r=rec('WR',{receptions:80,receiving_yards:1000,receiving_td:8,rushing_yards:0,rushing_td:0});const ppr=PF.scoreProjection(r,{rec:1,rec_yd:.1,rec_td:6});const half=PF.scoreProjection(r,{rec:.5,rec_yd:.1,rec_td:6});assert.equal(ppr.points-half.points,40);});
test('TE premium is applied as an incremental reception premium',()=>{const r=rec('TE',{receptions:70,receiving_yards:800,receiving_td:6,rushing_yards:0,rushing_td:0});const base=PF.scoreProjection(r,{rec:1,rec_yd:.1,rec_td:6});const premium=PF.scoreProjection(r,{rec:1,rec_te:1.5,rec_yd:.1,rec_td:6});assert.equal(premium.points-base.points,35);});
test('unsupported relevant scoring stays partial instead of becoming zero',()=>{const r=rec('WR',{receptions:80,receiving_yards:1000,rushing_yards:0,rushing_td:0});const x=PF.scoreProjection(r,{rec:1,rec_yd:.1,rec_td:6});assert.equal(x.completeness,'partial');assert.deepEqual(x.unsupported_keys,['rec_td']);});
test('rookies without projection records are not forced through veteran model',()=>{assert.equal(PF.classifyMissing({years_exp:0}),'rookie_model_required');});
test('experimental UI is firewalled from dynasty valuation code',()=>{const src=fs.readFileSync(require.resolve('../experimental-ui-v03.js'),'utf8');assert.equal(src.includes('calculateValuation'),false);assert.equal(src.includes('finalValue='),false);assert.match(src,/do not affect dynasty values|Dynasty values are unchanged/);});
test('dynasty value is identical with experimental display enabled or disabled',()=>{const league={total_rosters:12,roster_positions:['QB','RB','RB','WR','WR','TE','FLEX'],scoring_settings:{rec:1,pass_td:4}},context=Core.leagueContext(league),input={player:{full_name:'Example',position:'WR',years_exp:3},market:{name:'Example',pos:'WR',team:'GB',age:25,ecr:20,base:6000,format:'1qb'},context,projection:{points:250,pos:'WR'},neutralReplacement:{levels:{WR:150}},leagueReplacement:{levels:{WR:150}},tradeCount:0};const disabled=Core.calculateValuation(input),enabled=Core.calculateValuation({...input,experimental_projection_display:rec('WR',{receptions:100,receiving_yards:1400,receiving_td:15})});assert.deepEqual(enabled,disabled);assert.equal(enabled.finalValue,disabled.finalValue);});
