const test=require("node:test");
const assert=require("node:assert/strict");
const p=require("../lib/research-qa-protocol-v01.js");
const input={repository:"kw7t9rwhny-cyber/league-vector",commit_sha:"a".repeat(40),tree_sha:"b".repeat(40)};
function work(){const w={schema_version:p.WORK_ITEM_SCHEMA_VERSION,work_item_id:"pilot-proof-1",objective:"Read-only audit.",role:"research",risk:"low",input_identity:input,context_refs:["repo://README.md"],allowed_actions:["read_repository"],forbidden_actions:["merge","deploy","remediate"],expected_terminal_result:p.RESULT_SCHEMA_VERSION,qa_requirement:"one",founder_gate:true,confidentiality:"public",budget:{max_worker_runs:2},replay_identity:""};w.replay_identity=p.deriveReplayIdentity(w);return w;}
function result(role="research",run=11){return p.buildAuthoritativeResult({work_item:work(),role,role_instance_id:`${role}-1`,worker_run_id:run,run_attempt:1,upstream_result_ids:[],writer_identity:"github-actions[bot]",created_at:"2026-08-18T15:00:00Z",substance:{status:role==="research"?"COMPLETE":"PASS",claims_or_findings:["finding"],evidence_refs:["repo://README.md"],artifact_refs:[],limitations:"",recommended_next_action:"Founder review"}});}
test("proof artifact name binds the full canonical terminal result",()=>{const r=result();const n=p.proofArtifactName(r);const changed=structuredClone(r);changed.substance.claims_or_findings=["different finding"];assert.match(n,/^lv-rqa-proof-[a-f0-9]{64}$/);assert.notEqual(n,p.proofArtifactName(changed));});
test("exact run-scoped proof artifact validates",()=>{const r=result();assert.equal(p.validateRunProofArtifact(r,[{name:p.proofArtifactName(r),expired:false,workflow_run:{id:11}}]),true);});
test("missing run proof artifact fails closed",()=>{const r=result();assert.throws(()=>p.validateRunProofArtifact(r,[]),/missing_worker_run_proof_artifact/);});
test("proof for different terminal substance fails closed",()=>{const r=result();const forged=structuredClone(r);forged.substance.claims_or_findings=["forged"];assert.throws(()=>p.validateRunProofArtifact(forged,[{name:p.proofArtifactName(r),expired:false,workflow_run:{id:11}}]),/missing_worker_run_proof_artifact/);});
test("proof artifact from wrong run fails closed",()=>{const r=result();assert.throws(()=>p.validateRunProofArtifact(r,[{name:p.proofArtifactName(r),expired:false,workflow_run:{id:12}}]),/wrong_worker_run_proof_artifact/);});
test("expired proof artifact fails closed",()=>{const r=result();assert.throws(()=>p.validateRunProofArtifact(r,[{name:p.proofArtifactName(r),expired:true,workflow_run:{id:11}}]),/missing_worker_run_proof_artifact/);});
test("duplicate run proof artifacts fail closed",()=>{const r=result(),a={name:p.proofArtifactName(r),expired:false,workflow_run:{id:11}};assert.throws(()=>p.validateRunProofArtifact(r,[a,{...a,id:2}]),/duplicate_worker_run_proof_artifact/);});
