const test=require("node:test");
const assert=require("node:assert/strict");
const p=require("../lib/research-qa-protocol-v01.js");
const input={repository:"kw7t9rwhny-cyber/league-vector",commit_sha:"a".repeat(40),tree_sha:"b".repeat(40)};
function work(max=2){const w={schema_version:p.WORK_ITEM_SCHEMA_VERSION,work_item_id:`remediation2-${max}`,objective:"Read-only audit.",role:"research",risk:"low",input_identity:input,context_refs:["repo://README.md"],allowed_actions:["read_repository"],forbidden_actions:["merge","deploy","remediate"],expected_terminal_result:p.RESULT_SCHEMA_VERSION,qa_requirement:"one",founder_gate:true,confidentiality:"public",budget:{max_worker_runs:max},replay_identity:""};w.replay_identity=p.deriveReplayIdentity(w);return w;}
function substance(role,status){return {status,claims_or_findings:["finding"],evidence_refs:["repo://README.md"],artifact_refs:[],limitations:"",recommended_next_action:"Founder review"};}
function researchResult(w=work(),run=101){return p.buildAuthoritativeResult({work_item:w,role:"research",role_instance_id:"research-1",worker_run_id:run,run_attempt:1,upstream_result_ids:[],writer_identity:"github-actions[bot]",created_at:"2026-08-18T17:00:00Z",substance:substance("research","COMPLETE")});}
function qaResult(w,rr,status="PASS",run=202){return p.buildAuthoritativeResult({work_item:w,role:"qa",role_instance_id:"qa-1",worker_run_id:run,run_attempt:1,upstream_result_ids:[rr.result_id],writer_identity:"github-actions[bot]",created_at:"2026-08-18T17:05:00Z",substance:substance("qa",status)});}
function runFor(result,status="completed",conclusion="success"){return {id:Number(result.worker_run_id),run_attempt:result.run_attempt,event:"workflow_dispatch",path:p.WORKFLOW_PATHS[result.role],repository:{full_name:input.repository},head_branch:"main",run_started_at:"2026-08-18T16:59:00Z",status,conclusion};}
function completedEvent(conclusion="success",display_title="RQA Research issue #67"){return {workflow_run:{status:"completed",conclusion,event:"workflow_dispatch",path:p.WORKFLOW_PATHS.research,head_branch:"main",display_title}};}

test("Research run in_progress plus valid durable result cannot grant downstream authority",()=>{const r=researchResult();assert.throws(()=>p.validateRunProvenance(r,runFor(r,"in_progress",null),{repository:input.repository,now:"2026-08-18T17:01:00Z"}),/worker_run_not_completed/);});
test("Research run completed success plus valid durable result is eligible provenance",()=>{const r=researchResult();assert.equal(p.validateRunProvenance(r,runFor(r),{repository:input.repository,now:"2026-08-18T17:01:00Z"}),true);});
test("Research run completed failure is not eligible",()=>{const r=researchResult();assert.throws(()=>p.validateRunProvenance(r,runFor(r,"completed","failure"),{repository:input.repository,now:"2026-08-18T17:01:00Z"}),/worker_run_not_successful/);});
test("Research run completed cancelled is not eligible",()=>{const r=researchResult();assert.throws(()=>p.validateRunProvenance(r,runFor(r,"completed","cancelled"),{repository:input.repository,now:"2026-08-18T17:01:00Z"}),/worker_run_not_successful/);});
test("Research run completed timed_out is not eligible",()=>{const r=researchResult();assert.throws(()=>p.validateRunProvenance(r,runFor(r,"completed","timed_out"),{repository:input.repository,now:"2026-08-18T17:01:00Z"}),/worker_run_not_successful/);});
test("local persistence can correlate its own in_progress run without making it downstream-authoritative",()=>{const r=researchResult();assert.equal(p.validateRunProvenance(r,runFor(r,"in_progress",null),{repository:input.repository,now:"2026-08-18T17:01:00Z",requireCompleted:false}),true);assert.throws(()=>p.validateRunProvenance(r,runFor(r,"in_progress",null),{repository:input.repository,now:"2026-08-18T17:01:00Z"}),/worker_run_not_completed/);});
test("post-completion reconciliation accepts only successful Research completion and resolves issue",()=>assert.equal(p.validateResearchCompletionWake(completedEvent()),67));
test("post-completion reconciliation rejects failed cancelled and timed_out parents",()=>{for(const c of ["failure","cancelled","timed_out"])assert.throws(()=>p.validateResearchCompletionWake(completedEvent(c)),/research_completion_not_successful/);});
test("post-completion reconciliation rejects wrong workflow event ref and run-name correlation",()=>{for(const mutate of [e=>e.workflow_run.path=p.WORKFLOW_PATHS.qa,e=>e.workflow_run.event="push",e=>e.workflow_run.head_branch="feature",e=>e.workflow_run.display_title="Research #67"]){const e=completedEvent();mutate(e);assert.throws(()=>p.validateResearchCompletionWake(e));}});
test("repeated in_progress reconciliation observations cannot satisfy completion wake",()=>{const e=completedEvent();e.workflow_run.status="in_progress";for(let i=0;i<3;i++)assert.throws(()=>p.validateResearchCompletionWake(e),/research_completion_not_completed/);});
test("repeated successful completion notifications resolve the same issue without creating authority themselves",()=>{for(let i=0;i<3;i++)assert.equal(p.validateResearchCompletionWake(completedEvent()),67);});
test("max_worker_runs 1 allows Research dispatch then blocks prospective QA dispatch",()=>{const w=work(1);let d=p.route({work_item:w,research_results:[],qa_results:[],dispatches:[],usage:{worker_runs_used:0}});assert.equal(d.action,"DISPATCH_RESEARCH");const rr=researchResult(w);d=p.route({work_item:w,research_results:[rr],qa_results:[],dispatches:[],usage:{worker_runs_used:1}});assert.deepEqual({action:d.action,disposition:d.disposition,reason:d.reason},{action:"STOP",disposition:"BLOCKED",reason:"run_limit_exhausted"});});
test("max_worker_runs 2 allows QA when one run is already used",()=>{const w=work(2),rr=researchResult(w);const d=p.route({work_item:w,research_results:[rr],qa_results:[],dispatches:[],usage:{worker_runs_used:1}});assert.equal(d.action,"DISPATCH_QA");});
test("max_worker_runs 2 preserves valid QA PASS at exact two-run boundary",()=>{const w=work(2),rr=researchResult(w),qr=qaResult(w,rr,"PASS");const d=p.route({work_item:w,research_results:[rr],qa_results:[qr],dispatches:[],usage:{worker_runs_used:2}});assert.equal(d.action,"STOP");assert.equal(d.disposition,"PASS");assert.equal(d.reason,"founder_lead_terminal_gate");});
test("max_worker_runs 2 preserves valid QA FAIL at exact two-run boundary",()=>{const w=work(2),rr=researchResult(w),qr=qaResult(w,rr,"FAIL");const d=p.route({work_item:w,research_results:[rr],qa_results:[qr],dispatches:[],usage:{worker_runs_used:2}});assert.equal(d.disposition,"FAIL");assert.equal(d.reason,"founder_lead_terminal_gate");});
test("max_worker_runs 2 preserves valid QA BLOCKED at exact two-run boundary",()=>{const w=work(2),rr=researchResult(w),qr=qaResult(w,rr,"BLOCKED");const d=p.route({work_item:w,research_results:[rr],qa_results:[qr],dispatches:[],usage:{worker_runs_used:2}});assert.equal(d.disposition,"BLOCKED");assert.equal(d.reason,"founder_lead_terminal_gate");});
test("max_worker_runs 2 with two dispatches and absent QA result cannot create a third dispatch",()=>{const w=work(2),rr=researchResult(w);const d=p.route({work_item:w,research_results:[rr],qa_results:[],dispatches:[],usage:{worker_runs_used:2}});assert.equal(d.action,"STOP");assert.equal(d.reason,"run_limit_exhausted");});
test("max_worker_runs greater than 2 leaves unused budget and preserves terminal QA",()=>{const w=work(4),rr=researchResult(w),qr=qaResult(w,rr,"PASS");const d=p.route({work_item:w,research_results:[rr],qa_results:[qr],dispatches:[],usage:{worker_runs_used:2}});assert.equal(d.disposition,"PASS");});
test("terminal QA state is evaluated before budget can block hypothetical additional work",()=>{const w=work(2),rr=researchResult(w),qr=qaResult(w,rr,"PASS");assert.equal(p.checkBudget({budget:w.budget,worker_runs_used:2}).ok,false);const d=p.route({work_item:w,research_results:[rr],qa_results:[qr],dispatches:[],usage:{worker_runs_used:2}});assert.equal(d.disposition,"PASS");});
test("prospective budget semantics are explicit used plus one greater than max",()=>{assert.equal(p.checkBudget({budget:{max_worker_runs:2},worker_runs_used:0}).ok,true);assert.equal(p.checkBudget({budget:{max_worker_runs:2},worker_runs_used:1}).ok,true);assert.equal(p.checkBudget({budget:{max_worker_runs:2},worker_runs_used:2}).reason,"run_limit_exhausted");});
