const test=require("node:test"); const assert=require("node:assert/strict");
const p=require("../lib/research-qa-protocol-v01.js");
const input={repository:"kw7t9rwhny-cyber/league-vector",commit_sha:"a".repeat(40),tree_sha:"b".repeat(40)};
function work(overrides={}) {
 const base={schema_version:p.WORK_ITEM_SCHEMA_VERSION,work_item_id:"pilot-1",objective:"Inventory workflow entry points.",role:"research",risk:"low",input_identity:input,context_refs:["repo://.github/workflows"],allowed_actions:["read_repository"],forbidden_actions:["merge","deploy","remediate"],expected_terminal_result:p.RESULT_SCHEMA_VERSION,qa_requirement:"one",founder_gate:true,confidentiality:"public",budget:{max_worker_runs:4},replay_identity:""};
 Object.assign(base,overrides); base.replay_identity=p.deriveReplayIdentity(base); return base;
}
const substanceR={status:"COMPLETE",claims_or_findings:["found workflows"],evidence_refs:["repo://.github/workflows"],artifact_refs:[],limitations:"",recommended_next_action:"QA"};
const substanceQ=(status="PASS")=>({status,claims_or_findings:["independently checked"],evidence_refs:["repo://.github/workflows"],artifact_refs:[],limitations:"",recommended_next_action:"Founder review"});
function result(w,role,run,up=[],sub,ri,created_at="2026-08-18T15:00:00Z"){return p.buildAuthoritativeResult({work_item:w,role,role_instance_id:ri||`${role}-1`,worker_run_id:run,run_attempt:1,upstream_result_ids:up,writer_identity:"github-actions[bot]",created_at,substance:sub});}
function runMeta(role,id,{path,status="completed",conclusion="success",run_attempt=1,event="workflow_dispatch",repository=input.repository,head_branch="main",started="2026-08-18T14:59:00Z"}={}){return {id,run_attempt,event,path:path||p.WORKFLOW_PATHS[role],status,conclusion,repository:{full_name:repository},head_branch,run_started_at:started,created_at:started};}
const usage={worker_runs_used:0};

test("valid narrow v0.1 work item",()=>assert.equal(p.validateWorkItem(work()),true));
for(const value of ["dual","installed-state","security","none"]) test(`unsupported QA requirement ${value} rejected before routing`,()=>assert.throws(()=>p.route({work_item:work({qa_requirement:value}),usage,research_results:[],qa_results:[],dispatches:[]}),/invalid_qa_requirement/));
test("unsupported dependency field rejected",()=>assert.throws(()=>p.validateWorkItem(work({dependencies:["missing"]})),/unknown_field:dependencies/));
test("initial qa role rejected",()=>assert.throws(()=>p.validateWorkItem(work({role:"qa"})),/invalid_role/));
test("wrong expected terminal type rejected",()=>assert.throws(()=>p.validateWorkItem(work({expected_terminal_result:"other/v9"})),/invalid_expected_terminal_result/));
test("positive AI budget semantics rejected",()=>assert.throws(()=>p.validateWorkItem(work({budget:{max_worker_runs:4,max_ai_credits:1}})),/unknown_field:max_ai_credits/));
test("positive Actions runtime budget semantics rejected",()=>assert.throws(()=>p.validateWorkItem(work({budget:{max_worker_runs:4,max_actions_runtime_minutes:1}})),/unknown_field:max_actions_runtime_minutes/));
test("restricted work item cannot enter public v0.1 persistence path",()=>assert.throws(()=>p.validateWorkItem(work({confidentiality:"restricted-rd"})),/unsupported_confidentiality/));
test("confidential engineering work item cannot enter public v0.1 persistence path",()=>assert.throws(()=>p.validateWorkItem(work({confidentiality:"confidential-engineering"})),/unsupported_confidentiality/));
test("Founder stop is mandatory",()=>assert.throws(()=>p.validateWorkItem(work({founder_gate:false})),/invalid_founder_gate/));
test("model-authored provenance cannot establish trusted authority",()=>assert.throws(()=>p.buildAuthoritativeResult({work_item:work(),role:"research",role_instance_id:"research-1",worker_run_id:1,run_attempt:1,writer_identity:"model",created_at:"2026-08-18T15:00:00Z",substance:substanceR}),/untrusted_writer/));

test("valid worker run provenance is independently accepted",()=>{const r=result(work(),"research",11,[],substanceR);assert.equal(p.validateRunProvenance(r,runMeta("research",11),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),true)});
test("self-asserted forged worker run id is rejected",()=>{const r=result(work(),"research",999,[],substanceR);assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/wrong_worker_run_provenance/)});
test("wrong workflow identity is rejected",()=>{const r=result(work(),"research",11,[],substanceR);assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11,{path:p.WORKFLOW_PATHS.qa}),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/wrong_worker_workflow/)});
test("wrong run attempt provenance is rejected",()=>{const r=result(work(),"research",11,[],substanceR);assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11,{run_attempt:2}),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/wrong_run_attempt_provenance/)});
test("wrong worker repository is rejected",()=>{const r=result(work(),"research",11,[],substanceR);assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11,{repository:"other/repo"}),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/wrong_worker_repository/)});
test("non workflow_dispatch provenance is rejected",()=>{const r=result(work(),"research",11,[],substanceR);assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11,{event:"push"}),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/wrong_worker_event/)});
test("result predating asserted worker run is rejected",()=>{const r=result(work(),"research",11,[],substanceR,"research-1","2026-08-18T15:00:00Z");assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11,{started:"2026-08-18T15:00:01Z"}),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/worker_result_chronology_mismatch/)});
test("completed failed run cannot establish provenance",()=>{const r=result(work(),"research",11,[],substanceR);assert.throws(()=>p.validateRunProvenance(r,runMeta("research",11,{status:"completed",conclusion:"failure"}),{repository:input.repository,now:"2026-08-18T15:01:00Z"}),/worker_run_not_successful/)});

test("valid Research result makes QA eligible",()=>{const w=work(),r=result(w,"research",11,[],substanceR); const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage}); assert.equal(x.action,"DISPATCH_QA"); assert.equal(x.upstream_result_id,r.result_id);});
test("zero Research result dispatches Research once",()=>assert.equal(p.route({work_item:work(),research_results:[],qa_results:[],dispatches:[],usage}).action,"DISPATCH_RESEARCH"));
test("duplicate Research result blocks",()=>{const w=work(),r=result(w,"research",11,[],substanceR); const x=p.route({work_item:w,research_results:[r,r],qa_results:[],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.reason,"duplicate_terminal_result")});
test("malformed result blocks",()=>{const w=work(),r=result(w,"research",11,[],substanceR);r.substance.status="PASS";const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.reason,"invalid_status")});
test("wrong work item cannot satisfy Research",()=>{const w=work(),r=result(work({work_item_id:"other"}),"research",11,[],substanceR);const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage});assert.equal(x.action,"DISPATCH_RESEARCH")});
test("wrong input identity blocks current authority",()=>{const w=work(),r=result(w,"research",11,[],substanceR);r.input_identity={...r.input_identity,commit_sha:"c".repeat(40)};r.result_id=p.deriveResultId(r);const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.reason,"wrong_input_identity")});
test("wrong worker blocks exact terminal proof",()=>{const w=work(),r=result(w,"research",11,[],substanceR);const exp={work_item_id:w.work_item_id,role:"research",role_instance_id:"research-1",worker_run_id:12,run_attempt:1,input_identity:w.input_identity,upstream_result_ids:[]};assert.throws(()=>p.proveExactlyOneTerminal([r],exp),/missing_terminal_result/)});
test("wrong role instance does not satisfy",()=>{const w=work(),r=result(w,"research",11,[],substanceR,"research-x"); const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage});assert.equal(x.action,"DISPATCH_RESEARCH")});
test("stale result rejected by production validator",()=>{const w=work(),r=result(w,"research",11,[],substanceR); assert.throws(()=>p.validateTerminalResult(r,{work_item_id:w.work_item_id,role:"research",role_instance_id:"research-1",worker_run_id:11,run_attempt:1,input_identity:w.input_identity,upstream_result_ids:[],not_before:"2026-08-18T16:00:00Z"}),/stale_result/)});
test("replayed dispatch blocks duplicate wake-up",()=>{const w=work();const first=p.route({work_item:w,research_results:[],qa_results:[],dispatches:[],usage});const second=p.route({work_item:w,research_results:[],qa_results:[],dispatches:[first.dispatch_identity],usage});assert.equal(second.action,"STOP");assert.equal(second.reason,"replayed_dispatch")});
test("partial Research BLOCKED stops and does not dispatch QA",()=>{const w=work(),r=result(w,"research",11,[],{...substanceR,status:"BLOCKED"});const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage});assert.equal(x.disposition,"BLOCKED");assert.equal(x.action,"STOP")});
test("untrusted envelope writer fails closed",()=>{const w=work(),r=result(w,"research",11,[],substanceR);r.writer_identity="attacker";const x=p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.reason,"untrusted_writer")});
test("QA bound to exact Research result and input",()=>{const w=work(),r=result(w,"research",11,[],substanceR);const q=result(w,"qa",12,[r.result_id],substanceQ());const x=p.route({work_item:w,research_results:[r],qa_results:[q],dispatches:[],usage});assert.equal(x.disposition,"PASS");assert.equal(x.founder_gate,true)});
for (const verdict of ["PASS","FAIL","BLOCKED"]) test(`QA ${verdict} closes at Founder stop`,()=>{const w=work(),r=result(w,"research",11,[],substanceR),q=result(w,"qa",12,[r.result_id],substanceQ(verdict));const x=p.route({work_item:w,research_results:[r],qa_results:[q],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.disposition,verdict);assert.equal(x.reason,"founder_lead_terminal_gate")});
test("missing QA cannot produce green completion",()=>{const w=work(),r=result(w,"research",11,[],substanceR);assert.equal(p.route({work_item:w,research_results:[r],qa_results:[],dispatches:[],usage}).action,"DISPATCH_QA")});
test("duplicate QA cannot produce green completion",()=>{const w=work(),r=result(w,"research",11,[],substanceR),q=result(w,"qa",12,[r.result_id],substanceQ());const x=p.route({work_item:w,research_results:[r],qa_results:[q,q],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.reason,"duplicate_terminal_result")});
test("wrong upstream result blocks QA",()=>{const w=work(),r=result(w,"research",11,[],substanceR),q=result(w,"qa",12,["f".repeat(64)],substanceQ());const x=p.route({work_item:w,research_results:[r],qa_results:[q],dispatches:[],usage});assert.equal(x.action,"STOP");assert.equal(x.reason,"wrong_upstream_result")});
test("contradictory QA status impossible",()=>assert.throws(()=>p.buildAuthoritativeResult({work_item:work(),role:"qa",role_instance_id:"qa-1",worker_run_id:12,run_attempt:1,upstream_result_ids:["e".repeat(64)],writer_identity:"github-actions[bot]",created_at:"2026-08-18T15:00:00Z",substance:{...substanceQ("PASS"),status:"COMPLETE"}}),/invalid_status/));
test("run limit exhaustion stops progression",()=>{const x=p.route({work_item:work(),research_results:[],qa_results:[],dispatches:[],usage:{worker_runs_used:4}});assert.equal(x.reason,"run_limit_exhausted");assert.equal(x.action,"STOP")});
test("ambiguous write reconciles only from durable readback",()=>{const attempted={x:1};assert.deepEqual(p.reconcileWrite({before:[],attempted,after:[attempted]}),{ok:true,state:"committed"});assert.equal(p.reconcileWrite({before:[],attempted,after:[]}).ok,false);assert.equal(p.reconcileWrite({before:[],attempted,after:[attempted,attempted]}).reason,"duplicate_authoritative_write")});
test("false-green worker completion rejected when terminal result absent",()=>{const exp={work_item_id:"pilot-1",role:"research",role_instance_id:"research-1",worker_run_id:11,run_attempt:1,input_identity:input,upstream_result_ids:[]};assert.throws(()=>p.proveExactlyOneTerminal([],exp),/missing_terminal_result/)});
test("dispatch identity changes with immutable input",()=>{const a=p.deriveDispatchIdentity({work_item_id:"x",role_instance_id:"research-1",input_identity:input});const b=p.deriveDispatchIdentity({work_item_id:"x",role_instance_id:"research-1",input_identity:{...input,commit_sha:"c".repeat(40)}});assert.notEqual(a,b)});
test("no remediation action exists in router outputs",()=>assert.equal(p.route.toString().includes("REMEDIATE"),false));
test("telemetry unavailable cost remains nullable not an authority ceiling",()=>{const t=p.telemetryRecord({work_item_id:"x",role:"research",role_instance_id:"research-1",started_at:"2026-08-18T15:00:00Z",ended_at:"2026-08-18T15:01:00Z",terminal_disposition:"COMPLETE"});assert.equal(t.ai_credits,null);assert.equal(t.actions_runtime_minutes,null)});
test("dispatch payload is pointer only; durable issue is authority",()=>{const w=work();const issue={number:77,user:{login:"founder",id:1},body:p.taggedRecord(p.MARKERS.workItem,w)};assert.equal(p.parseWorkItemIssue(issue).work_item_id,w.work_item_id);assert.equal(p.validateWorkItemCreatorAuthority(issue,{login:"founder",id:1,permission:"write"}),true);assert.throws(()=>p.validateWorkItemCreatorAuthority(issue,{login:"attacker",id:2,permission:"write"}),/untrusted_work_item_creator/)});
test("dispatch record identity is deterministic and immutable-input bound",()=>{const w=work(),d=p.buildDispatchRecord({work_item:w,role:"research",role_instance_id:"research-1",created_at:"2026-08-18T15:00:00Z"});assert.equal(p.validateDispatchRecord(d),true);const bad={...d,input_identity:{...d.input_identity,tree_sha:"c".repeat(40)}};assert.throws(()=>p.validateDispatchRecord(bad),/dispatch_identity_mismatch/)});
test("untrusted marker comment is quarantined and grants no authority",()=>{const w=work(),r=result(w,"research",11,[],substanceR);const c={user:{login:"attacker",id:2,type:"User"},body:p.taggedRecord(p.MARKERS.result,r)};assert.deepEqual(p.parseAuthoritativeResults([c]),[])});
test("lookalike Actions bot without canonical numeric id is quarantined",()=>{const w=work(),r=result(w,"research",11,[],substanceR);const c={user:{login:"github-actions[bot]",id:1,type:"Bot"},body:p.taggedRecord(p.MARKERS.result,r)};assert.deepEqual(p.parseAuthoritativeResults([c]),[])});
test("canonical Actions bot comment remains authoritative",()=>{const w=work(),r=result(w,"research",11,[],substanceR);const c={user:{login:"github-actions[bot]",id:41898282,type:"Bot"},body:p.taggedRecord(p.MARKERS.result,r)};assert.equal(p.parseAuthoritativeResults([c]).length,1)});
