const fs=require('node:fs');const path=require('node:path');const Core=require('../core-v08.js');const Data=require('../football-data-v08.js');const V1=require('./benchmark-projections.js');const H=require('./ingest-historical-data.js');const B=require('../projection-benchmark-v08.js');const P=require('../projection-v03.js');
const SEASONS=Array.from({length:11},(_,i)=>2015+i),FOLDS=[2020,2021,2022,2023,2024,2025],SLEEPER_URL='https://api.sleeper.app/v1/players/nfl';
function write(d,n,v){fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,n),JSON.stringify(v,null,2)+'\n');}
function activeRelevant(id,p){const pos=Data.normalizePosition(p?.position||p?.fantasy_positions?.[0]).normalized_position;return p?.active===true&&P.POSITIONS.includes(pos)?{id,pos}:null;}
function yearsExp(p){const n=Number(p?.years_exp);return Number.isFinite(n)?n:null;}
function rankReport(rows){const result=[];const limits={QB:[12,24],RB:[12,24,36],WR:[12,24,36,48],TE:[12,24],DL:[12,24],LB:[12,24],DB:[12,24]};for(const pos of P.POSITIONS){const r=rows.filter(x=>x.position===pos).sort((a,b)=>b.actual_points-a.actual_points),pred=[...r].sort((a,b)=>b.predicted_points-a.predicted_points);for(const n of limits[pos]||[]){if(r.length<n)continue;const actual=new Set(r.slice(0,n).map(x=>x.gsis_id)),projected=pred.slice(0,n).map(x=>x.gsis_id),hit=projected.filter(x=>actual.has(x)).length;result.push({position:pos,top_n:n,overlap:hit,precision:hit/n,recall:hit/n});}}return result;}
async function run(o={}){const seasons=o.seasons||SEASONS,folds=(o.folds||FOLDS).filter(x=>seasons.includes(x)),dir=path.resolve(o.outputDir||'data/reports/projection-v03'),cache=path.resolve(o.cacheDir||'.cache/league-vector/projection-v03'),base=await V1.load(seasons,{cacheDir:cache,refresh:o.refresh});
const playersUrl=Data.nflverseUrls(seasons[0]).players,playersCsv=(await H.fetchText(playersUrl,path.join(cache,'players.csv'),{refresh:o.refresh,timeoutMs:45000})).text,rawPlayers=Core.parseCsv(playersCsv),players=rawPlayers.map(Data.normalizeNflversePlayer),birth=Object.fromEntries(players.filter(p=>p.identity.gsis_id&&p.bio.birth_date).map(p=>[p.identity.gsis_id,p.bio.birth_date])),ps=B.aggregatePlayerSeasons(base.observations),pred=[];for(const fold of folds)pred.push(...P.predictFold(ps.filter(r=>r.season<=fold),fold,birth));if(pred.some(x=>x.history_seasons.some(y=>y>=x.target_season)))throw new Error('Temporal leakage detected');
const selection=P.compare(pred,folds),fantasy=P.fantasyBacktest(pred,selection),uncertainty=P.uncertainty(pred,selection),selectedMap=new Map(selection.map(x=>[`${x.position}|${x.target}`,x.selected.model]));
const groups=new Map();for(const r of pred){if(selectedMap.get(`${r.position}|${r.target}`)!==r.model)continue;const k=`${r.gsis_id}|${r.position}|${r.target_season}`,x=groups.get(k)||{gsis_id:r.gsis_id,position:r.position,target_season:r.target_season,pred:{},actual:{}};x.pred[r.target]=r.prediction;x.actual[r.target]=r.actual;groups.set(k,x);}const rankRows=[];for(const x of groups.values()){const missing=(P.REQUIRED[x.position]||[]).filter(k=>!Number.isFinite(x.pred[k])||!Number.isFinite(x.actual[k]));if(!missing.length)rankRows.push({...x,predicted_points:P.scoreReference(x.pred,x.position),actual_points:P.scoreReference(x.actual,x.position)});}const rankings=rankReport(rankRows);
const sleeperText=(await H.fetchText(SLEEPER_URL,path.join(cache,'sleeper-players.json'),{refresh:o.refresh,timeoutMs:45000})).text,sleeper=JSON.parse(sleeperText),crosswalk=Data.buildCrosswalk(sleeper,rawPlayers,{},new Date().toISOString()),hist=P.index(ps),uncMap=new Map(uncertainty.map(x=>[`${x.position}|${x.target}`,x])),models=new Map();for(const s of selection)models.set(`${s.position}|${s.target}`,P.finalModel(ps,s.position,s.target,birth,s,2026));
const counts={projection_ready:0,rookie_model_required:0,insufficient_history:0,identity_unresolved:0,unsupported_position:0,missing_required_inputs:0,data_unavailable:0},byPosition={},projections=[],review=[];for(const [sleeperId,sp] of Object.entries(sleeper)){const rel=activeRelevant(sleeperId,sp);if(!rel)continue;const pos=rel.pos;byPosition[pos]||={projection_ready:0,rookie_model_required:0,insufficient_history:0,identity_unresolved:0,missing_required_inputs:0};const mapping=crosswalk.mappings[sleeperId];let status;if(!mapping){status=yearsExp(sp)===0?'rookie_model_required':'identity_unresolved';review.push({sleeper_id:sleeperId,name:sp.full_name||null,position:pos,status});}else{const h=P.history(hist,mapping.gsis_id,2026);if(!h.length)status=yearsExp(sp)===0?'rookie_model_required':'insufficient_history';else{const line={},used={};for(const t of P.TARGETS[pos]||[]){const m=models.get(`${pos}|${t}`),v=m?.buildFor(mapping.gsis_id);if(Number.isFinite(v)){line[t]=v;used[t]=m.name;}}const clean=P.sanitizeLine(line,pos),missing=(P.REQUIRED[pos]||[]).filter(k=>!Number.isFinite(clean.stats[k]));status=missing.length?'missing_required_inputs':'projection_ready';const intervals={};for(const t of Object.keys(clean.stats)){const u=uncMap.get(`${pos}|${t}`);if(u)intervals[t]={p80_low:Math.max(0,clean.stats[t]-u.p80),p80_high:clean.stats[t]+u.p80,p90_low:Math.max(0,clean.stats[t]-u.p90),p90_high:clean.stats[t]+u.p90};}projections.push({league_vector_player_id:mapping.league_vector_player_id,gsis_id:mapping.gsis_id,sleeper_id:sleeperId,name:sp.full_name||[sp.first_name,sp.last_name].filter(Boolean).join(' '),position:pos,team:sp.team||null,projection_status:status,projected_stats:clean.stats,models:used,uncertainty:intervals,confidence:P.confidence(h.length,missing,true),history_seasons:h.map(x=>x.season),missing_inputs:missing,warnings:clean.corrections.map(c=>`sanity_correction:${c.field}:${c.rule}`),model_version:P.VERSION,projection_date:new Date().toISOString(),experimental:true,production_projection_eligible:false,dynasty_value_eligible:false});}}
counts[status]=(counts[status]||0)+1;byPosition[pos][status]=(byPosition[pos][status]||0)+1;}
const readiness={generated_at:new Date().toISOString(),counts,by_position:byPosition,total_current_relevant:Object.values(counts).reduce((a,b)=>a+b,0),crosswalk_summary:crosswalk.summary};const selectedCounts={};for(const s of selection)selectedCounts[s.selected.model]=(selectedCounts[s.selected.model]||0)+1;const ageAblation={with_age_better:selection.filter(x=>x.age_ablation.preferred==='with_age').length,without_age_better:selection.filter(x=>x.age_ablation.preferred==='without_age').length,insufficient:selection.filter(x=>x.age_ablation.preferred==='insufficient_evidence').length};
const summary={version:P.VERSION,seasons,folds,observations:base.observations.length,player_seasons:ps.length,historical_predictions:pred.length,selected_models:selectedCounts,age_ablation:ageAblation,complete_fantasy_players:fantasy.complete_players,current_2026_projection_records:projections.length,current_projection_ready:counts.projection_ready,rookie_model_required:counts.rookie_model_required,identity_unresolved:counts.identity_unresolved,tree_model:{implemented:false,reason:'Deferred: v0.3 first completes tuned ridge/age ablation/shrinkage and live-readiness; no dependency added without evidence it is needed.'},production_eligible:false,dynasty_value_eligible:false};
write(dir,'summary.json',summary);write(dir,'model-selection.json',selection);write(dir,'fantasy-backtest.json',fantasy);write(dir,'top-n-rankings.json',rankings);write(dir,'uncertainty.json',uncertainty);write(dir,'2026-readiness.json',readiness);write(dir,'2026-projections.json',projections);write(dir,'identity-review.json',review);return{summary,selection,fantasy,rankings,uncertainty,readiness,projections};}
if(require.main===module){const a={};for(let i=2;i<process.argv.length;i+=2)a[process.argv[i].replace(/^--/,'')]=process.argv[i+1];run({seasons:(a.seasons||SEASONS.join(',')).split(',').map(Number),folds:(a.folds||FOLDS.join(',')).split(',').map(Number),cacheDir:a.cache,outputDir:a.outputDir,refresh:a.refresh==='true'}).then(x=>console.log(JSON.stringify(x.summary,null,2))).catch(e=>{console.error(e.stack||e);process.exit(1);});}module.exports={run,rankReport};